### ISSUE TITLE
Erro ao confirmar alteracao de morada

### ISSUE THREAD

**Issue by brunoamancio** [amagovpt/autenticacao.gov#10]
Eu fiz a alteracao de morada e recebi o código da confirmacao de alteracao. Ao entrar com o código, recebo o erro genérico STR_CHANGE_ADDRESS_ERROR:

![image](https://user-images.githubusercontent.com/3150473/73140313-e2e27800-4077-11ea-9bf8-1575fbfe4484.png)

O erro é mostrado em **gapi.cpp**  [gapi.cpp](https://github.com/amagovpt/autenticacao.gov/blob/1a3308faef771552e4901febd59b1d90ccf2c8da/pteid-mw-pt/_src/eidmw/eidguiV2/gapi.cpp)

No meu caso, nao há problema algum com a conexao com internet, nem com servidor proxy (nao uso). Infelizmente nao sei o código do erro, já que nada é retornado na mensagem. no caso de uma mensagem genérica, acho que ajudaria saber o código do erro, mesmo que apenas nos debug logs.

As mensagens nos logs nao ajudam em nada:
![image](https://user-images.githubusercontent.com/3150473/73140525-132b1600-407a-11ea-913c-abe3a30b7dba.png)

**Comment by agrr** [comment]
Viva, 
deve ter algum erro registado no ficheiro de log em:
"C:\Program Files\Portugal Identity Card\log\.PTEID_0.log"
