### ISSUE TITLE
Problema a exportar alguns certificados em Ubuntu 20.04

### ISSUE THREAD

**Issue by jccmartins** [amagovpt/autenticacao.gov#100]
Boa tarde,

Detetei um problema a exportar os certificados de autenticação e assinatura digital do cartão de cidadão através da aplicação Autenticação.gov.

Configuração:
- Ubuntu 20.04
- Aplicação Autenticação.gov versão 3.7.0

Quando exporto os certificados e tento ver o seu conteúdo usando o "Certificate Viewer" padrão (clicando no ficheiro ou correndo num terminal gcr-viewer &lt;filepath&gt;), aparece a seguinte mensagem de erro:
![gcr-viewer cert.der](https://user-images.githubusercontent.com/36761733/170718117-3f6189d4-73fb-4b2e-a2dd-a300600e0997.png)

Para os restantes certificados (ECRaizEstado 002, Cartão de Cidadão 006, EC de Autenticação do Cartão de Cidadão 0017 e EC de Assinatura Digital Qualificada do Cartão de Cidadão 0017) a exportação funciona corretamente.

Percebi que o problema acontece porque a aplicação Autenticação.gov escreve mais bytes do que o tamanho real do certificado. Ao correr `hexdump cert.der` verificamos isto:
![hexdump cert.der](https://user-images.githubusercontent.com/36761733/170719487-6a7572a2-8ff1-4948-affe-605df3767410.png)

Se removermos os bytes com valor 0 do fim do certificado, funciona corretamente.

**Comment by agrr** [comment]
Este issue está corrigido na versão 3.8.0 da aplicação.
