### ISSUE TITLE
Debian 11: Erro - Package 'qt5-default' has no installation candidate + LogBase.cpp:46:10: fatal error: PCSC/wintypes.h: No such file or directory

### ISSUE THREAD

**Issue by jj-matos** [amagovpt/autenticacao.gov#101]
Ao instalar as dependências aparece este erro: 'Package 'qt5-default' has no installation candidate'
Ao tentar a compilação fazendo : 'qmake pteid-mw.pro'
Dá o seguinte erro: qmake: 'could not exec '/usr/lib/qt5/bin/qmake': No such file or directory'
Pesquisei uma solução tendo encontrado este link: https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04
Tentei a solução indicada tendo efetuado: 'sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools'
Tentei de novo a compilação fazendo : 'qmake pteid-mw.pro'
Dá as seguintes mensagens: 
"Project MESSAGE: Release build!
Project WARNING: PKG_NAME has not been set! Assuming PKG_NAME=pteid"
Efetuei: 'make'
Tendo obtido o erro constante da imagem anexa:
![Screenshot from 2022-05-29 16-50-30](https://user-images.githubusercontent.com/24443094/170878717-b4ae04b2-cdaa-4010-bdf1-daddbf79b3b9.png)
Procuro solução para instalar a aplicação do cartão do cidadão em Debian 11. Obrigado.

**Comment by agrr** [comment]
Boa tarde,

falta instalar o pacote `libpcsclite-dev` que está na lista de dependências que temos no README do projeto.

Em Debian é muito útil esta página para pesquisar que versões existem do pacote X na versão stable do Debian p.ex. ou até que pacote tem o ficheiro Y:
https://www.debian.org/distrib/packages

**Comment by jj-matos** [comment]
A solução está aqui:
É preciso criar um fake package do qt5-default.
