### ISSUE TITLE
Problema com as definições do selo de assinatura no menu "Assinatura"

### ISSUE THREAD

**Issue by jccmartins** [amagovpt/autenticacao.gov#103]
Boa tarde,

No menu "Assinatura" da aplicação Autenticação.gov existem problemas com as definições do selo de assinatura (definições abaixo da secção "Pré-visualização").

Configuração:
- Ubuntu 20.04
- Aplicação Autenticação.gov versão 3.7.0

Passos para reproduzir o problema:
1. Abrir a aplicação Autenticação.gov no menu "Assinatura".
![1](https://user-images.githubusercontent.com/36761733/174105598-b5def55d-6acd-4e59-a93d-a9bfa2da657e.png)
2. Alterar o tipo de assinatura para "Outros ficheiros" e novamente para "PDF".
![2](https://user-images.githubusercontent.com/36761733/174105595-1169a805-ffdd-42a1-ab61-fc06cfabdaaf.png)
Neste passo as definições "Visível" e "Reduzida" passam a poder ser alteradas, ao contrário do que acontece na imagem do passo 1.
3. Desativar e ativar a definição "Visível".
4. Alterar o tipo de assinatura para "Outros ficheiros".
![3](https://user-images.githubusercontent.com/36761733/174105592-ba1f4dfd-f6c0-4a69-9802-b41e319b12ae.png)
Neste passo a opção "Última" passa a poder ser alterada quando o tipo de assinatura é "Outros ficheiros".

Estes problemas não afetam a experiência do utilizador e penso que também não afetam o resultado da assinatura digital, mas achei por bem mencioná-los na mesma.

**Comment by agrr** [comment]
Este issue foi corrigido em 98a9ab9512e9e044f9b09200760c706944040a23. A correção ficará disponível na próxima release da aplicação 3.9.0.

Obrigado pelo reporte.
