### ISSUE TITLE
Erro com DLL pteidlib_dotnet

### ISSUE THREAD

**Issue by Vitorjol37** [amagovpt/autenticacao.gov#104]
Boa tarde,

Estou a desenvolver uma pequena aplicação em ASP.NET C# para leitura de alguns dados do CC.

-Adicionei a referência pteidlib_dotnet.dll ao projecto VS
-Faço o init ao SDK PTEID_ReaderSet.initSDK()
-Compilo o projeto;

 Quando acedo ao site, este pára a application pool referente.

Qual a resolução para o problema? Será que falta algum DLL ?

Nota: no servidor IIS, instalei a aplicação Autenticacao.GOV.

Obrigado.

**Comment by agrr** [comment]
A DLL _pteidlib_dotnet_ tal como os restantes SDKs disponibilizados por este projeto estão preparados para serem utilizados em aplicações desktop.
Por exemplo no portal Autenticação.gov no contexto de autenticação com CC a aplicação que comunica com o cartão é o plugin do mesmo nome que é uma aplicação desktop Java.

Na configuração que descreve poderia ser tecnicamente possível ler um CC na aplicação ASP.net a correr num Windows Server mas em termos de arquitetura não faz muito sentido.
