### ISSUE TITLE
Raspberry Pi Assinatura com PIN 

### ISSUE THREAD

**Issue by TiagoFonseca99** [amagovpt/autenticacao.gov#105]
Ao utilizar a SDK para efetuar uma assinatura digital com o PIN de assinatura, não consigo introduzir qualquer digito na janela de pop-up que requisita o PIN.

A aplicação funciona perfeitamente noutros ambientes.

**Comment by agrr** [comment]
Boa tarde, 
apesar de não ser um sistema suportado oficialmente tentaremos ajudar.

Para aumentar o nível de log do middleware adicionar estas linhas ao ficheiro `$HOME/.config/pteid.conf`:
```
[logging]
log_filenumber=50
log_level=debug
```
Após executar de novo a função de assinatura no SDK, precisamos do output que é gerado no ficheiro `~/.PTEID_0.log`.
