### ISSUE TITLE
Suporte para arquiteturas ARM

### ISSUE THREAD

**Issue by amserra** [amagovpt/autenticacao.gov#107]
Boa tarde. Estou a trabalhar num mac com M1 e a testar a integração através da API PKCS#11 e do Middleware. Quando inicializo como descrito [aqui](https://amagovpt.github.io/docs.autenticacao.gov/manual_sdk.html), em ambos os casos dá-me o seguinte erro:

`dlopen(/usr/local/lib/libpteidpkcs11.dylib, 0x0006): tried: '/usr/local/lib/libpteidpkcs11.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libpteidpkcs11.2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`

Desta forma, questiono se irá haver suporte para este tipo de arquiteturas. Obrigado

**Comment by Tragio** [comment]
Olá @amserra 👋  estou a ter o mesmo problema. Chegaste arranjar uma forma de o contornar? 🤔

**Comment by agrr** [comment]
Boa tarde,
a versão 3.12.0 do SDK a lançar brevemente terá bibliotecas em formato _universal binary_ (ARM64 + x86_64).

Está previsto que seja lançada em pré-release aqui no Github, antes de ser publicada no autenticacao.gov.pt.

**Comment by Tragio** [comment]
Muito obrigado @agrr! 🙏 Já agora, há alguma previsão de lançamento?

**Comment by agrr** [comment]
Já está disponível a pre-release da versão 3.12.0: https://github.com/amagovpt/autenticacao.gov/releases/tag/v3.12.0

**Comment by amserra** [comment]
Obrigado @agrr . Vou fechar o issue.
