### ISSUE TITLE
Autenticação Gov impede enrollment na Azure Active Directory

### ISSUE THREAD

**Issue by pt3244** [amagovpt/autenticacao.gov#112]
Bom dia,
Serve o presente issue para avisar que a aplicação Autenticação Gov impede o enrollment com sucesso numa Azure Active Directory.

Segue abaixo o extracto do Event Viewer, que suponho que possa ser usado nos vossos contactos com a Microsoft para apurar o erro ou, pelo menos, para a MS prevenir que seja um erro obtuso com código hexadecimal (por parte do Windows) como acontece atualmente.

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Application Error"/>
		<EventID Qualifiers="0">1000</EventID>
		<Version>0</Version>
		<Level>2</Level>
		<Task>100</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2022-09-14T15:01:49.9105058Z"/>
		<EventRecordID>15281</EventRecordID>
		<Correlation/>
		<Execution ProcessID="12364" ThreadID="0"/>
		<Channel>Application</Channel>
		<Computer>*</Computer>
		<Security/>
	</System>
	<EventData>
		<Data>svchost.exe_DmEnrollmentSvc</Data>
		<Data>10.0.22000.527</Data>
		<Data>e6f2ec65</Data>
		<Data>pteidcommon.dll</Data>
		<Data>3.8.0.4656</Data>
		<Data>628b89ce</Data>
		<Data>c0000005</Data>
		<Data>000000000000a8f3</Data>
		<Data>57a4</Data>
		<Data>01d8c84ad70f1b82</Data>
		<Data>C:\WINDOWS\system32\svchost.exe</Data>
		<Data>C:\WINDOWS\system32\pteidcommon.dll</Data>
		<Data>3391d30a-11e6-4b05-beca-451bee52e4ee</Data>
		<Data/>
		<Data/>
	</EventData>
</Event>
```

**Comment by agrr** [comment]
Bom dia, uma vez que não conseguimos no imediato testar esse cenário, pedimos o seguinte despiste:
verificar se nesse PC foi registado um certificado de assinatura Chave Móvel Digital ?

Para isso deve verificar no `certmgr.msc` se existe um certificado com o valor "EC de Chave Móvel Digital de Assinatura Digital Qualificada do Cartão de Cidadão (...)" na coluna "Issued By/Emitido por".

Em caso afirmativo, pedimos que tentem apagar esse certificado e repetir o teste de enrollment.

**Comment by pt3244** [comment]
Não posso confirmar porque entretanto desinstalei o Autenticação Gov para poder fazer o enrollment.

Eventualmente outra pessoa poderá confirmar a situação.

**Comment by agrr** [comment]
Foi possível identificar e corrigir um bug que originava crash na DLL `pteidcommon` coincidente com o registo do Event Viewer apresentado.
Este só acontecia se o processo que utiliza a `pteidcommon.dll` fosse um Windows service.
Será disponibilizada a correção na próxima versão da aplicação: 3.9.0

**Comment by agrr** [comment]
Issue já resolvido na versão 3.9.0 publicada ontem.
