### ISSUE TITLE
faulting module name: pteidcommon.dll (CredentialProvider)

### ISSUE THREAD

**Issue by TiagoMartins2** [amagovpt/autenticacao.gov#113]
Im trying to customize the CredentialProvider from Windows in C++, to accept the CC card but, when i add any code from the pteidlib.lib the credential doesn't load and in the event viewr i find these 2  errors.
What do i need to do to fix this?
<img width="419" alt="error2" src="https://user-images.githubusercontent.com/107430687/193816611-f7a7c453-e7e7-4147-82f0-fcda3b7dfacc.png">
<img width="410" alt="error1" src="https://user-images.githubusercontent.com/107430687/193816614-e5333547-7177-4d7d-a026-474593e36ae2.png">

**Comment by agrr** [comment]
Bom dia Tiago, vou responder em Português porque faz mais sentido aqui no contexto do projeto.
Este crash no módulo `pteidcommon.dll` já está corrigido no repositório e a correção será disponibilizada na próxima release 3.9.0:
https://github.com/amagovpt/autenticacao.gov/commit/df814b3b9a8731861d1f804db1ee2f33322f0278

No sentido de desbloquear os seus desenvolvimentos sem ter de esperar pela 3.9.0 poderá compilar apenas esta DLL no VS 2017 em modo Release e substituir em `C:\Windows\System32`. 
Sugiro compilar apenas esta DLL porque facilita bastante o processo de build já que este módulo não tem dependências externas de outras libs. 
As alterações que foram implementadas desde a v 3.8.0 não deverão quebrar a compatibilidade por isso deverá funcionar a substituição desta DLL sem atualizar as restantes.

**Comment by TiagoMartins2** [comment]
Bom dia André, obrigado pela resposta, para obter apenas o pteidcommon.dll preciso então de fazer build do "pteidcommon.rc"?

**Comment by agrr** [comment]
É necessário compilar o projeto com o nome 'common' na solution:
https://github.com/amagovpt/autenticacao.gov/blob/master/pteid-mw-pt/_src/eidmw/_Builds/Autenticacao.gov.sln

**Comment by TiagoMartins2** [comment]
Obrigado André, já está a funcionar.

**Comment by agrr** [comment]
Issue já resolvido na versão 3.9.0 publicada ontem.
