### ISSUE TITLE
Compilação em Fedora

### ISSUE THREAD

**Issue by joaquimrocha** [amagovpt/autenticacao.gov#12]
Estou a tentar compilar em Fedora 31, e está a ser desafiante. Consegui dar a volta ao facto de precisar de openssl 1.0 e o pacote nesta versão de Fedora ser 1.1 (e são incompatíveis).
A dependência em `xml-security-c` está mais complicada já que o header `xsec/utils/XSECDOMUtils.hpp` parece não existir nesta versão da dependência.

Qual é a versão de Fedora com que têm feito os builds? (Que também não funcionam nas últimas versões da distro devido à dependência no openssl 1.0)

**Comment by jorgedsmatias** [comment]
Tive exactamente o mesmo problema a tentar colocar a funcionar num Debian 10 (aka _buster_) em Agosto. Na realidade foi mais para um Raspbian _buster_ . Nesta versão da Debian também já openssl 1.1. As funções e estruturas de dados de openssl, que este software usa, no openssl 1.0 já estava descontinuadas. E apareciam os alertas inclusivamente. Na versão 1.1 desapareceram.

Eu fiz um fork do projecto e criei um branch (https://github.com/jorgedsmatias/eidmw/tree/openssl11_support) para resolver o problema.
Na altura consegui modificar todo o código que precisava para que passasse na compilação, mas ainda há diversos problemas a lidar com certificados e com a adição de assinaturas nos documentos PDF.
O meu código foi modificado para suportar, tanto quanto possível, OpenSSL 0.9.8, OpenSSL 1.0 e OpenSSL 1.1, mas só testei a sério contra a última versão. Também foi alterado para suportar a libxml-security-c20, em vez da libxml-security-c17, e a libxerces-c3.2. Todas estas bibliotecas passaram a abstrair as suas estruturas de dados, o que implica que deve ser sempre usadas funções para a criação e manipulação dessas estruturas.



Não recomendo usar o meu código por ser um fork da v3.0.16, que não incluí uma série de novidades incluídas neste projecto.
Mas já pedi à equipa da AMA para olhar para o meu código e ver o que pode aproveitar e como integrar as alterações na versão actual do software.

**Comment by marado** [comment]
Também há um repositório com mais ou menos as mesmas alterações, mas com a v3.0.21, em https://github.com/marado/autenticacao.gov . De notar que esta versão (que reutiliza parte do trabalho do @jorgedsmatias ) tem vários problemas, identificados em https://github.com/marado/autenticacao.gov/issues .

**Comment by Tony-il-Capo** [comment]
Estou com os mesmos problemas a tentar correr o 'middleware' em Debian 11 (Bullseye).

Os forks com modificações não me servem, pois segundo entendi não é possível assinar digitalmente...

Quase todo o pessoal aqui que usa Linux também tem o mesmo problema, só alguem com distribuições (bastante) antigas é que consegue correr/compilar isto.

**Comment by lverissimo** [comment]
idem comigo. Uma atualização para versões mais recentes seria interessante.

**Comment by joaquimrocha** [comment]
Obrigado pelas respostas. Quando tiver tempo vou tentar dar uma vista de olhos.
Numa aplicação desta natureza, acho que é importante actualizar estas bibliotecas por razões de segurança.

O meu objectivo é fazer um flatpak da autenticacao.gov , para poder usar de forma mais estável (cada vez que tento usar mesmo os pacotes, já nada funciona devido às versões, e uma versão em flatpak pode melhorar isso). Claro que posso sempre adicionar versões mais antigas dos pacotes, mas era bom poder usar as versões recentes (até porque já vêm algumas com o runtime de freedesktop).

**Comment by Tony-il-Capo** [comment]
Não conseguir correr isto em Linux é frustante, ter o sistema (bastante!) desatualizada para isto funcionar não é solução e ter de (comprar e) instalar windows de propósito ainda menos.

Um "Flatpak" ou "Snap" acho que seria a solução, pois deixa de depender de bibliotecas instaladas no OS, mas pode também criar alguns problemas, tais como este [mencionado aqui](https://github.com/amagovpt/autenticacao.gov/issues/5#issuecomment-567022503)

**Comment by agrr** [comment]
Boa tarde,

já foi disponibilizado no site oficial um build 3.1.0 para suportar as últimas versões de Ubuntu (19.10), Fedora (31) e OpenSUSE (Leap 15.1).
Publicámos também o branch de código **openssl-migration** que foi usado para estes builds e onde estão a ser feitos os desenvolvimentos relativos à migração de OpenSSL e bibliotecas relacionadas.

Desta forma pode ser compilado o software para outras distribuições não suportadas pelos builds oficiais.
