### ISSUE TITLE
Debian 11 - Erro na actualização do plugin Autenticacão.gov

### ISSUE THREAD

**Issue by jj-matos** [amagovpt/autenticacao.gov#120]
Estou a querer atualizar o plugin no Debian 11.
Seguindo as instruções depois do download do ficheiro deb indicado para esta mesma diretoria, dá o erro que se apresenta na imagem.
Agradeço ajuda para efetuar a atualização com sucesso. Obrigado.
![autentiacao-gov](https://user-images.githubusercontent.com/24443094/210184448-ffe87f9f-25a8-4bb6-a4a6-882614acc24e.png)

**Comment by agrr** [comment]
Bom dia,
Verifique o valor da variável PATH com o comando `echo $PATH`, deveria ter nessa variável a diretoria `/usr/sbin` entre outras localizações de programas essenciais do sistema.

Se não fizer parte da lista de diretorias da $PATH, deve ser essa a causa dos erros apresentados, `/usr/sbin` é a localização dos comandos `ldconfig` e `start-stop-daemon`

**Comment by jj-matos** [comment]
Bom dia,
Obrigado pela ajuda. Fiz como indicou. Aqui está o resultado:
/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v16.14.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

**Comment by agrr** [comment]
Não consigo confirmar o comportamento exato no Debian 11 mas essa PATH para um utilizador normal parece-me OK, mas pelo que percebo para comandos executados com `sudo` ou diretamente numa shell root devem ter acesso a uma PATH com essas diretorias.

**Comment by jj-matos** [comment]
Estou a entrar na minha área com su e password. E depois executo os comandos.

**Comment by jj-matos** [comment]
Resolvido. Em vez de entrar na minha área com su, executei diretamente o comando com sudo. 
Obrigado.
