### ISSUE TITLE
Erro a detetar Leitor de Cartões (Versão 3.9.1 Linux Flatpak)

### ISSUE THREAD

**Issue by joaoleonor** [amagovpt/autenticacao.gov#121]
Ao tentar ler um cartão de cidadão com a v/ aplicação, dá-me sempre o erro "Leitor de Cartões não detetado"
O meu pc funciona com o SO Ubuntu 22.04 e tenho instalada a v/ aplicação versão 3.9.1 (flatpak).
Testei com dois leitores de cartões diferentes, e noutro pc também com Ubuntu 22.04, em ambos os casos deu sempre o mesmo erro.
Testei também a versão 3.8.1, para Ubuntu 22.04 (versão pacote .deb) e deu o mesmo erro.
Tenho os pacotes pcsclite/pcscd instalados tal como é recomendado.

**Comment by agrr** [comment]
Boa tarde,
Poderá ser uma questão relativa com o pcscd em Ubuntu 22.04, nós na equipa de projeto ainda só testámos esse sistema em máquina virtual e não encontrámos problemas a esse nível.

Tem mais informação aqui no blog de um dos developers do software de smartcards em Linux:
https://ludovicrousseau.blogspot.com/2022/10/ubuntu-2204-and-pcscd-auto-start-failure.html 

Pode também verificar o estado de suporte dos seus leitores nesta tabela, normalmente funcionam bem os que estão nas categorias "supported" e "should work":
https://ccid.apdu.fr/ccid/section.html

**Comment by joaoleonor** [comment]
Bom dia,

Antes de mais agradeço a reposta rápida.
A informação que me forneceu está certissima, é um bug do ubuntu que já foi reportado, relativamente ao arranque automático do deamon do PC/SC.
No link que me forneceu tem a solução para o mesmo, basta executar o comando
sudo systemctl enable pcscd.socket
Depois, reiniciar o pc e fica resolvido, o Ubuntu já deteta os leitores de cartão, e por consequência, a vossa app também.
Fica aqui a nota para quem se deparar com este problema.

Mais uma vez muito obrigado!
