### ISSUE TITLE
Assinatura múltipla via interface linha comandos - Opção Pasta Destino

### ISSUE THREAD

**Issue by mrtsilva** [amagovpt/autenticacao.gov#122]
Boa Tarde,

Ao utilizar assinatura  via Interface de linha de comandos ( de acordo com a seção 6 da documentação ) indica que:
 --destino DESTINO (-d DESTINO): configura a pasta de destino do ficheiro assinado. A pasta de destino não será pedida ao utilizador no momento da assinatura.

Confirmo que não me pede a pasta de destino quando tento assinar um só documento.
Exemplo Linux: "eidguiV2 sign -d /home/USER/ /home/USER/Doc.pdf"
Exemplo Windows: "C:\Program Files\Portugal Identity Card\pteidguiV2.exe" sign -d C:\Users\USER\Desktop TestFile.pdf"

No entanto, o comportamento quando se tenta assinar múltiplos documentos faz aparecer o popup de escolha da pasta de destino dos documentos (já dentro da autenticação.gov.pt).
Exemplo Linux: "eidguiV2 sign -d /home/USER/ /home/USER/Doc.pdf /home/USER/Doc1.pdf"
Exemplo Windows: "C:\Program Files\Portugal Identity Card\pteidguiV2.exe" sign -d C:\Users\USER\Desktop C:\Users\USER\Desktop\TestFile.pdf C:\Users\USER\Desktop\TestFile2.pdf"

Pergunto se podem avaliar a possibilidade de colocar todos os documentos assinados na mesma pasta ou no limite ter de especificar uma pasta de destino para cada documento individualmente.

Agradeço

**Comment by agrr** [comment]
Confirmamos que existia este issue do parâmetro -d (--destino) no caso de assinatura com Chave Móvel.
Está corrigido na versão 3.10.0 da aplicação já disponível.

Obrigado pelo feedback @mrtsilva
