### ISSUE TITLE
Suporte para OpenSSL 1.1 e xml-security-c20, usado em todas as distribuições Linux 2019+

### ISSUE THREAD

**Issue by jorgedsmatias** [amagovpt/autenticacao.gov#13]
O middleware do cartão de cidadão não compila contra OpenSSL 1.1, xml-security-c 2.0 e libxerces-c3.2 .
Tenho um fork da versão 3.0.16 criado [1] , com um branch "openssl11_support" [2], específico para o desenvolvimento das alterações ao código que permitam compilar contra estas 3 bibliotecas.
O build passa em Debian/Raspbian 10, com uma função add_signingCertificate(PKCS7_SIGNER_INFO *si, ...) desactivada [3]. Há algumas alterações a fazer ainda. 

Referências: 
- [1] https://github.com/jorgedsmatias/eidmw
- [2] https://github.com/jorgedsmatias/eidmw/tree/openssl11_support
- [3] https://github.com/jorgedsmatias/eidmw/issues/1

**Comment by ACamposPT** [comment]
Este problema já esta ultrapassado e será em breve colocado no master. Actualmente está no seguinte branch:
https://github.com/amagovpt/autenticacao.gov/tree/openssl-migration
