### ISSUE TITLE
Funcionalidade: Passagem de ficheiros a assinar por parametro para a aplicação

### ISSUE THREAD

**Issue by nunomourinho** [amagovpt/autenticacao.gov#14]
A aplicação do cartão de cidadão neste momento ainda não pode ser utilizada em linha de comandos.
Existem várias aplicações que podem beneficiar desta funcionalidade.

**Sintaxe sugerida:**

pteidguiV2.exe <ficheiros.pdf> <pasta_de_destino>

**Exemplo:**

pteidguiV2.exe ficheiro1.pdf ficheiro2.pdf ... c:\assinados

**Modo de Funcionamento**

1) A aplicação abre com a página assinatura -> avançada com os ficheiros já adicionados.
2) O utilizador escolhe onde colocar a assinatura e assina (chave movel ou cartão)
3) Os ficheiros são colocados na pasta_de_destino.

**Comment by ACamposPT** [comment]
Esta funcionalidade está a ser implementada. Logo que tenhamos novidades voltamos.

**Comment by Justinopsky** [comment]
Já existe alguma novidade quanto a essa funcionalidade?

**Comment by nunomourinho** [comment]
:)

Em seg., 27 de jul. de 2020 às 12:29, Justinopsky <notifications@github.com>
escreveu:

**Comment by ACamposPT** [comment]
Já está implementada. Vai ser colocada na próxima versão. Esta prevista sair em Agosto.

**Comment by ACamposPT** [comment]
@nunomourinho @Justinopsky Já está em produção. Obrigado pelas sugestões.

https://amagovpt.github.io/autenticacao.gov/user_manual.html#interface-de-linha-de-comandos

**Comment by nunomourinho** [comment]
Vou testar :)

Muito, muito, muito obrigado :)

Em ter., 29 de set. de 2020 às 17:21, Adriano Campos <
notifications@github.com> escreveu:
