### ISSUE TITLE
Java SDK versão 3.11.0

### ISSUE THREAD

**Issue by FexaMachado** [amagovpt/autenticacao.gov#142]
Bom dia.

Preciso que a minha aplicação, através do SDK, use os serviços online para obter a morada do cartão de cidadão.
Depois de compilar o código fonte para obter as dependências e o ficheiro .jar em #141 . Testei em Windows e deu-me o seguinte erro: `java.lang.NoClassDefFoundError: pt/gov/cartaodecidadao/PTEID_ReaderSet`

Precisava que o SDK funcionasse para Linux e Windows simultaneamente.
Como devo proceder?

**Comment by agrr** [comment]
No caso do Windows se estiver instalado o MSI disponível em https://www.autenticacao.gov.pt/web/guest/cc-aplicacao,  o SDK Java fica localizado em `C:\Program Files\Portugal Identity Card\sdk\` e as bibliotecas nativas subjacentes também ficam instaladas no sistema. 

O build que fez no contexto do issue #141 só serve para Linux de forma a ultrapassar as limitações do pacote Flatpak.

Ver esta secção do manual:
https://amagovpt.github.io/docs.autenticacao.gov/manual_sdk.html#atualiza%C3%A7%C3%B5es-do-middleware

**Comment by FexaMachado** [comment]
Havia um problema ao assinar o .jar que estava a provocar o problema.
Depois de resolvido, o .jar funcionou para Linux e Windows.
