### ISSUE TITLE
Utilização de certificado da ordem para autenticação

### ISSUE THREAD

**Issue by luisabreu** [amagovpt/autenticacao.gov#147]
Bom dia.

Estou a desenvolver uma aplicação Web com autenticação integrada com CC e Chave Móvel através de SAML. Esta autenticação está completa, mas gostaria de adicionar uma opção extra de login  através de um certificado digital (ex.: ordem dos advogados). Pelo que estou a ver no vosso manual, esta integração é possível, mas estou com algumas dúvidas sobre o funcionamento desta opção de autenticação.

No ponto 6, é dito que quando "fornecedor de serviços requisitar a autenticação ou a obtenção de atributos junto do Autenticação.Gov, o utilizador terá de apresentar um certificado válido para proceder à sua autenticação ou recolha de atributos.".  

Para além disso, também é dito que:

"Quando um fornecedor de serviços solicitar atributos terá de especificar quais os atributos e qual o certificado que o utilizador deverá fornecer na autenticação. Por predefinição será usada a cadeia de certificação do Cartão de Cidadão."

E finalmente, no ponto 6.1:

"A seleção do certificado a ser usada é da responsabilidade do portal da entidade, que deverá indicar explicitamente qual a forma de autenticação que pretende que seja usada no Autenticação.Gov. Por sua vez, o Autenticação.Gov irá solicitar ao utilizador a identificação digital correspondente."

Mas como é que se dá esta indicação? É feita aquando do registo no vosso portal? Ou existe algum atributo de um elemento ou extensão que tem de ter um determinado  valor na mensagem de autenticação SAML enviada? Infelizmente, não consegui encontrar nenhuma informação útil sobre este tópico no manual.

Será que me podem dar mais informação sobre este tópico?

Obrigado

**Comment by agrr** [comment]
Boa noite,

Os issues deste projeto servem para questões/dúvidas sobre o middleware do Cartão de Cidadão e Chave Móvel, identificado para o utilizador final como Aplicação Autenticação.gov para computador.

Para questões sobre integração com o serviço de autenticação com CC e CMD deve usar o e-mail de contacto que consta no seguinte README:
https://github.com/amagovpt/doc-AUTENTICACAO
