### ISSUE TITLE
Verificar documento assinado. 

### ISSUE THREAD

**Issue by joaoportela** [amagovpt/autenticacao.gov#148]
Este talvez não seja o sítio certo para esta pergunta... Mas já procurei e não encontrei a resposta.

Como é que posso verificar por quem é que um documento foi assinado e que a assinatura é autêntica?

Obrigado pela ajuda.

**Comment by agrr** [comment]
Existem 2 alternativas fiáveis e que validam assinaturas usando as listas de entidades certificadoras da União Europeia:
https://eidas.ec.europa.eu/efda/tl-browser/#/screen/home

1. O Adobe Acrobat Reader em Windows e MacOS
2. Utilizadores com algum conhecimento técnico podem usar a instância portuguesa do validador de assinaturas DSS que aceita assinaturas em documentos PDF e em formato XAdES:
https://validador.autenticacao.gov.pt/
