### ISSUE TITLE
PTEID_Pin.unlockPin() não desbloqueia o PIN da morada...

### ISSUE THREAD

**Issue by mpfa** [amagovpt/autenticacao.gov#155]
Tenho o PIN da morada bloqueado (triesleft = 0) e consultando a documentação encontrei o metodo unlockPin​(java.lang.String pszPuk, java.lang.String pszNewPin, PTEID_ulwrapper triesLeft, long flags) da classe PTEID_Pin

Tentei utilizar a função, aparece a janela do middleware a solicitar o PUK, PIN e confirmação do PIN, mas não acontece nada... o PIN da morada continua bloqueado...

O que devo colocar no parâmetro "flags"?

**Comment by ACamposPT** [comment]
Olá,
O middleware é o mesmo para o Cidadão e serviços. No entanto, o desbloqueio do PIN só pode ser efetuado pelos serviços, usando o PUK ou os dados biométricos. Deve se dirigir aos serviços para isso.

**Comment by mpfa** [comment]
Obrigado pelo feedback.

Infelizmente quem mudou o PIN original da morada (0000) acaba por ficar com
o PIN bloqueado pelas tentativas dos diversos serviços (clínicas,etc) em
ler a morada utilizando o PIN por defeito...

Eu só me apercebi que o meu estava bloqueado ao tentar obter a morada do
meu cartão...

Será melhor então voltar a colocar o PIN por defeito ou isto vai acontecer
novamente de certeza...

A terça, 9/01/2024, 17:22, Adriano Campos ***@***.***>
escreveu:
