### ISSUE TITLE
Carregar no botão "Assinar com CMD" não funciona Fedora 31

### ISSUE THREAD

**Issue by r3pek** [amagovpt/autenticacao.gov#16]
Estou a usar Fedora 31 e instalei a última versão disponível que já instala nesta versão de Fedora (congrats for that).

Normalmente não tenho leitor de cartões comigo pelo que uso a funcionalidade de assinar documentos com a Chave Móvel Digital, mas após adicionar o PDF a assinar e pressionar no botão, nada acontece (em Windows abre logo a janela para escolher o caminho onde guardar o ficheiro assinado).

Há alguma dependência que falta ou é mesmo só algum erro/fail "camuflado"?

**Comment by agrr** [comment]
Viva Carlos,

que output aparece na consola ao escolher "Assinar com Chave Móvel" ?
O comando para executar no terminal é `/usr/local/bin/eidguiV2`

**Comment by r3pek** [comment]
boas @agrr 
Foi logo das 1ªs coisas que tentei, não aparece nada.

**Comment by r3pek** [comment]
Só para acrescentar, tenho um portátil (que tem leitor de cartões [não sei se tem a ver]), que funciona sem problemas. No desktop não abre nada (quando carrego no botão).

**Comment by agrr** [comment]
Qual a versão do QT instalado no desktop ?
`rpm -qi qt5-qtbase`

Estamos a preparar uma alteração que vai eliminar um uso de uma API privada do QT que temos nessa operação e que torna os builds demasiado dependentes da versão que usamos para compilar.
Suspeitamos que será esta a razão desse erro na assinatura CMD.

**Comment by r3pek** [comment]
Name        : qt5-qtbase
Version     : 5.13.2
Release     : 2.fc31
Architecture: x86_64
Install Date: Fri 31 Jan 2020 08:44:33 AM WET

**Comment by pt3244** [comment]
@r3pek consegues confirmar que o bug já não acontece numa das versões do Fedora atualmente suportadas? (F36, F37)

**Comment by r3pek** [comment]
@Segment0895  Confirmo (até me esqueci deste report)
