### ISSUE TITLE
Credenciais CMD Assinatura Digital SDK (Desktop)

### ISSUE THREAD

**Issue by stivencamara** [amagovpt/autenticacao.gov#163]
Boas,

Ao tentar testar assinar (CMD) um documento da Assinatura Digital do SDK (Desktop) conforme o link https://amagovpt.github.io/docs.autenticacao.gov/manual_sdk.html#assinatura-digital, estou a obter o erro "**Unmapped error: -506454516**".

A lembrar que já tenho as crendeciais de pré-prod. 

A minha dúvida é: as crendeciais são as mesmas para o SDK? Ou é necessária uma específica para o SDK? Uma vez que já desenvolvi a integração com o webservice da AMA e as credenciais estão a funcionar.

PTEID_CMDSignatureClient.setCredentials(BASIC_AUTH_USER, BASIC_AUTH_PASSWORD, BASIC_AUTH_APPID);

Obrigado.

**Comment by agrr** [comment]
Bom dia,
Sim, as credenciais são as mesmas que utiliza para o webservice.

Poderá estar a utilizar o ambiente de produção já que é necessário configuração no SDK se pretendemos utilizar outro ambiente da CMD.
Deve adicionar estas 2 linhas na inicialização da assinatura para utilizar o **serviço de pré-produção**:

```
PTEID_Config config = new PTEID_Config(PTEID_Param.PTEID_PARAM_CMD_HOST);
config.setString("preprod.cmd.autenticacao.gov.pt");
```

**Comment by agrr** [comment]
Devemos acrescentar que esta configuração através da classe `PTEID_Config` fica guardada localmente, o que significa que numa próxima execução no mesmo computador vai utilizar o CMD_HOST de pré-produção mesmo se retirar a chamada `PTEID_Config.setString()`.

A configuração local que deve rever em caso de dúvida fica guardada em Windows no registry em `HKEY_CURRENT_USER\SOFTWARE\PTEID\general` e em MacOS no ficheiro `$HOME/Library/Preferences/pteid.conf `

**Comment by stivencamara** [comment]
Muito obrigado.

Crie uma Pull Request com essa alteração no Manual do SDK, espero que possa ajudar.

https://github.com/amagovpt/docs.autenticacao.gov/pull/4

**Comment by rguedes** [comment]
@stivencamara a implementação CMD é apenas da assinatura ou também tem SCAP?
