### ISSUE TITLE
Erro leitura cartão com JAVA SDK

### ISSUE THREAD

**Issue by AndreasPilgrim** [amagovpt/autenticacao.gov#166]
Bom dia,

Com a versão 3.12.0 surge um erro ao ler o cartão a partir do Java SDK:

java.lang.UnsatisfiedLinkError: pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_XMLDoc_SWIGUpcast(J)J
	at pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_XMLDoc_SWIGUpcast(Native Method)
	at pt.gov.cartaodecidadao.PTEID_XMLDoc.<init>(PTEID_XMLDoc.java:15)
	at pt.gov.cartaodecidadao.PTEID_EId.<init>(PTEID_EId.java:15)
	at pt.gov.cartaodecidadao.PTEID_EIDCard.getID(PTEID_EIDCard.java:43)

Para já tenho "solucionado" este problema por:

1. Desinstalar a versão 3.12.0
2. Reiniciar PC
3. Instalar a versão 3.12.0
4. Reiniciar PC

Usualmente resolve, no entanto em MacOS aparenta não resolver persistindo o erro.

**Comment by agrr** [comment]
Boa tarde,

O SDK Java das versões anteriores (`pteidlibj.jar`) não é compatível com as bibliotecas da versão 3.12.0, devido a manutenção do projeto que levou à remoção de classes como a `PTEID_XMLDoc`

Aconselhamos a seguir as recomendações do manual do SDK quanto a atualizações:
https://amagovpt.github.io/docs.autenticacao.gov/manual_sdk.html#atualizações-do-middleware

**Comment by AndreasPilgrim** [comment]
@agrr A remoção de classes não é problemática, até porque após reiniciar máquinas Windows após cada desinstalação/instalação "resolve" o problema.

Só pondero se poderá existir algum problema no processo de atualização de outras versões para esta, visto ter começado a dar este erro depois de se atualizar o Autenticação.GOV para o 3.12.

**Comment by AndreasPilgrim** [comment]
Estive a validar e nós carregamos sempre a library diretamente, no caso do mac libpteidlibj.2.0.0.dylib que vai parar a /usr/local/lib, sendo sempre a atualizada.

Podem validar se há algum problema nessa library nesta nova versão?
