### ISSUE TITLE
Fails to build due to to extra const (with GNU Classpath)

### ISSUE THREAD

**Issue by a36233** [amagovpt/autenticacao.gov#17]
g++ -c -pipe -fPIC -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=gnu++11 -fPIC -DPTEID_35 -DEIDMW_PREFIX=/usr/local -DEIDMW_CMN_EXPORT -DEIDMW_EIDLIB_EXPORTS -I. -I. -I../applayer -I../dialogs -I../common -I../cardlayer -I../eidlib -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -isystem /usr/include/PCSC -I/usr/lib/qt/mkspecs/linux-g++ -o eidlibJava_Wrapper.o GeneratedFiles/eidlibJava_Wrapper.cpp
GeneratedFiles/eidlibJava_Wrapper.cpp: In function ‘__jbyteArray* Java_pt_gov_cartaodecidadao_pteidlibJava_1WrapperJNI_PTEID_1ByteArray_1GetBytes(JNIEnv*, jclass, jlong, jobject)’:
GeneratedFiles/eidlibJava_Wrapper.cpp:3621:53: error: invalid conversion from ‘const jbyte*’ {aka ‘const signed char*’} to ‘jbyte*’ {aka ‘signed char*’} [-fpermissive]
 3621 |     jenv->SetByteArrayRegion(jresult,0,arg1->Size(),(const jbyte*) result);
      |                                                     ^~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     const jbyte* {aka const signed char*}
In file included from GeneratedFiles/eidlibJava_Wrapper.cpp:178:
/usr/include/jni.h:1471:77: note:   initializing argument 4 of ‘void _Jv_JNIEnv::SetByteArrayRegion(jbyteArray, jsize, jsize, jbyte*)’
 1471 |   void SetByteArrayRegion (jbyteArray val0, jsize val1, jsize val2, jbyte * val3)
      |                                                                     ~~~~~~~~^~~~
make[1]: *** [Makefile:1132: eidlibJava_Wrapper.o] Error 1
make[1]: Leaving directory '/home/brunofernandes/AUR/cartaodecidadao/src/autenticacao.gov/pteid-mw-pt/_src/eidmw/eidlibJava_Wrapper'
make: *** [Makefile:401: sub-eidlibJava_Wrapper-make_first-ordered] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by agrr** [comment]
Esse erro de build não ocorre no branch openssl-migration usando o OpenJDK 11.
Nesse sistema, a que versão do OpenJDK pertence o ficheiro /usr/include/jni.h ?

**Comment by a36233** [comment]
Bom dia,
Pelos vistos no meu sistema Arch Linux, no /usr/include/jni.h eles colocam a substituição GNU (classpath) das bibliotecas de java.
http://www.gnu.org/software/classpath/

As da Oracle são mantidas num PATH próprio por versão e.g.:
/usr/lib/jvm/java-13-openjdk/include/jni.h
/usr/lib/jvm/java-11-openjdk/include/jni.h
/usr/lib/jvm/java-10-openjdk/include/jni.h
/usr/lib/jvm/java-8-openjdk/include/jni.h
/usr/lib/jvm/java-7-openjdk/include/jni.h

# Criei links simbólicos temporariamente para re-testar
/usr/lib/jvm/java-11-openjdk/include/linux/jni.h -> /usr/include/jni.h
/usr/lib/jvm/java-11-openjdk/include/linux/jni_md.h -> /usr/include/jni_md.h
E passou a compilar.

No Archlinux é possivel manter todas as versões instaladas de java e depois usam a ferramenta archlinux-java para definir qual a que está a ser usada a cada momento.
A qual altera os links simbolicos para a versão correcta i.e.

$ archlinux-java status
Available Java environments:
  java-10-openjdk
  java-11-openjdk (default)
  java-13-openjdk
  java-7-openjdk
  java-8-openjdk

$ cd /usr/lib/jvm/ 
$ ls -a -l 
total 404
drwxr-xr-x   7 root root   4096 Apr  8 08:10 .
drwxr-xr-x 349 root root 385024 Apr  8 08:03 ..
lrwxrwxrwx   1 root root     15 Apr  8 08:10 default -> java-11-openjdk
lrwxrwxrwx   1 root root     15 Apr  8 08:10 default-runtime -> java-11-openjdk
drwxr-xr-x   7 root root   4096 Jun 21  2019 java-10-openjdk
drwxr-xr-x   7 root root   4096 Jan 18 11:10 java-11-openjdk
drwxr-xr-x   7 root root   4096 Feb  1 11:28 java-13-openjdk
drwxr-xr-x   6 root root   4096 Oct  1  2019 java-7-openjdk
drwxr-xr-x   6 root root   4096 Feb  1 11:29 java-8-openjdk

$ cd default
$ ls -a -l 
total 32
drwxr-xr-x 7 root root 4096 Jan 18 11:10 .
drwxr-xr-x 7 root root 4096 Apr  8 08:10 ..
drwxr-xr-x 2 root root 4096 Jan 18 11:10 bin
lrwxrwxrwx 1 root root   19 Jan 17 06:39 conf -> /etc/java11-openjdk
drwxr-xr-x 4 root root 4096 Jan 18 11:10 demo
drwxr-xr-x 3 root root 4096 Jan 18 11:10 include
drwxr-xr-x 2 root root 4096 Jan 18 11:10 jmods
lrwxrwxrwx 1 root root   34 Jan 17 06:39 legal -> /usr/share/licenses/java11-openjdk
drwxr-xr-x 6 root root 4096 Jan 18 11:10 lib
lrwxrwxrwx 1 root root   14 Jan 17 06:39 man -> /usr/share/man
-rw-r--r-- 1 root root 1158 Jan 17 06:39 release

$ find ./ -type f -name "jni*.h"
./include/jni.h
./include/linux/jni_md.h

**Comment by agrr** [comment]
Obrigado pelo feedback. Alterei apenas o título para que a informação fique mais acessível para quem no futuro se depare com o mesmo problema.
