### ISSUE TITLE
Desempenho na leitura do cartão cidadao (primeiro valor)

### ISSUE THREAD

**Issue by jaomeireles** [amagovpt/autenticacao.gov#179]
Estou a desenvolver uma aplicação C# de comunicação com o cartão de cidadão. Acontece que em alguns terminais, o sistema é muito lento com tempos entre 6 a 7 segundos, chegando por vezes a demorar mais de 10 segundos para obter o primeiro dado do cartão de cidadão (Ex: ".getGivenName()"). Os seguintes dados são "instantâneos". Estes tempos também são reproduzíveis na aplicação "autenticação.gov" nos mesmos terminais.

No "pc" de desenvolvimento (windows 11), por exemplo, os tempos de leitura são entre 2 a 3 segundos.

Já foi desativado o antivírus e a aplicação executada com permissões de administrador mantendo-se o mesmo comportamento.

Existe algo a ter em atenção relativamente à aplicação/sistema operativo por forma a tentar melhorar estes tempos?

**Comment by agrr** [comment]
Bom dia,

excluindo a possibilidade de estarem a ser utilizados leitores diferentes, no Windows existe uma actividade de registo de certificados que pode atrasar a leitura do Cartão de Cidadão através do SDK.

É possível desativar o componente minidriver que gera mais leituras no cartão logo que é inserido, se não necessitarem de utilizar assinaturas através dos certificados do CC registados no Windows (via CryptoAPI/CNG).

Isto pode-se fazer de 2 formas:
1. Afetando todos os smartcards utilizados no PC: desligar o serviço Windows "Certificate propagation" (CertPropSvc)
2. Desativando o minidriver do CC apenas, apagar as chaves de registo com nomes começados por "Pteid" criadas em `HKLM\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\`

**Comment by jaomeireles** [comment]
Boa tarde!

   Após as alterações sugeridas houve uma melhoria ligeira no tempo de obtenção dos dados do cartão (cc) , estabilizando nos 5 segundos.

  Vou contextualizar melhor o cenário:

O objetivo é o desenvolvimento de uma aplicação em .Net 8 ( a correr no "systray") que, após a introdução do cc, despolete uma ação que obtenha os dados "públicos" e os envie para um determinado endpoint.
	
1) Pretende-se atualizar uma aplicação já existente com alguns anos que utiliza um dll antigo "eidpt". Atualmente, todo processo definido anteriormente demora entre 1 e 2 segundos.
	
2) Na nova versão os tempos obtidos (dependem do terminal), apenas para a leitura dos dados "públicos" do cc, demora cerca de 5 segundos (por vezes existem alguns picos). 

Realizados os seguintes testes, todos eles devolvendo resultados equivalentes ( por defeito em qualquer tipo de processador):
		1) Aplicação em .Net 8
		2) Aplicação em .Net 6
		3) Aplicação em .Net Framework 4.8
		4) Aplicação Java

Envio abaixo configurações definidas na aplicação:	
![Captura de ecrã 2024-09-03 142358](https://github.com/user-attachments/assets/60690e95-3faf-4386-b521-c6bc1d18347c)
![Captura de ecrã 2024-09-03 142418](https://github.com/user-attachments/assets/02989666-dc42-4486-bd5e-59b34d922a0d)

3) Após as alterações indicadas abaixo no registro do windows em "HKLM->SOFTWARE->PTEID->configuretool" houve outra melhoria dos tempos para obtenção entre os 3.5 e os 4 segundos (ainda estamos a avaliar se os tempos são consistentes/permanentes, mas parece que sim),
![image](https://github.com/user-attachments/assets/c03c3107-f954-47e2-80aa-4352fc43fe79)

4) Não sei se tem algum impacto ou significado, mas pelo nome, o ficheiro "pteidmdrv64.dll" encontra-se da diretoria "Windows\System32" e o ficheiro "pteidmdrv32" na "Windows\SysWOW64" (caso haja impacto poderá existir outros ficheiros?)

5) O leitor utilizado para testes foi o mesmo em ambas as aplicações (antiga a funcionar e nova em desenvolvimento):  Ewent EW1052, mas o comportamento é equivalente com outros leitores.

Sabem informar se estes tempos obtidos são os esperados?

Agradeço desde já o tempo dispendido!!!

**Comment by agrr** [comment]
Os tempos entre os 3.5 e 5 segundos parecem-nos normais para a leitura dos dados públicos dos CCs da geração 1, emitidos até 10 de Junho deste ano. 
No novo modelo de Cartão de Cidadão a leitura é bastante mais rápida no SDK (cerca de 50% do tempo de leitura) também no interface de contacto , isto é utilizando os mesmos leitores de cartões.

Quanto à questão sobre a DLL `pteidmdrv32.dll`: esta é a versão 32 bits do componente minidriver, não tem impacto no desempenho em sistemas Windows 64-bits já que o serviço "Certificate propagation" irá carregar sempre a DLL `pteidmdrv64.dll`.
Existem de facto entradas de registo na secção de 32-bits do registry em Windows x64 com referâncias para essa DLL mas apenas para compatibilidade com aplicações 32-bit.
