### ISSUE TITLE
Problema nas instruções de linha de comando

### ISSUE THREAD

**Issue by tiago-as** [amagovpt/autenticacao.gov#18]
No manual de instruções do Software do Cartão de Cidadão, as instruções de linha de comando apenas indicam para instalar o .deb após o seu download. No entanto, ao executar o comando no manual o sistema de pacotes fica partido devido à falta de dependências. Nesta circunstância, o administrador de sistemas é obrigado a executar comandos adicionais para recuperar o sistema de pacotes.

Seria possível alterarem as instruções para que garantissem todas as dependências a instalar antes de se instalar o pacote deb?

A minha sugestão seria:

```
# comandos testados para Ubuntu 20.04
sudo apt install libxalan-c111 libxml-security-c20 qml-module-qt-labs-platform
sudo dpkg -i Autenticacao.gov_Ubuntu_20_x64.deb
```
Muito obrigado

**Comment by tiago-as** [comment]
Bom dia, só para confirmar se viram este ticket, actualizei o comentário acima para 20.04"

**Comment by agrr** [comment]
Foram melhoradas no manual da v3.2.0 as instruções para instalação em Linux incluindo dependências.
