### ISSUE TITLE
Instalação da aplicação Autenticação.gov

### ISSUE THREAD

**Issue by Quimfus** [amagovpt/autenticacao.gov#186]
Mensagem de erro "A aplicação pt.gov.autenticacao/x86_64/master requer o runtime org.kde.Platform/x86_64/5.15-23.08, que não foi localizado".

**Comment by agrr** [comment]
Boa tarde,

em Ubuntu é necessário adicionar o repositório Flathub para poder instalar esta aplicação e muitas outras em formato Flatpak.
Instruções em: https://flatpak.org/setup/Ubuntu

**Comment by Quimfus** [comment]
Boa tarde,
 Após a reinstalação do flatpak e flathub, consegui instalar a app Autenticação.gov.
Obrigado!

**Comment by dfvilhena** [comment]
Boa tarde,
Comento apenas para dizer que também me deparo com o mesmo problema, inclusive após seguir os passos sugeridos.

**Comment by f3r73ch** [comment]
Caros

Quando o desenvolvimento da aplicacao foi adjudicada nao incluia uma versao para Linux ? 

F
