### ISSUE TITLE
dotnet 8.0 - pteidlib_dotnet8+.dll

### ISSUE THREAD

**Issue by snufffgit** [amagovpt/autenticacao.gov#191]
Bom dia,

Tentei criar uma aplicação Console Application em MacOS, utilizando a nova dll. No entanto ao invocar obtenho um erro.

```

pt.portugal.eid.PTEID_ReaderSet.initSDK();
var reader = pt.portugal.eid.PTEID_ReaderSet.instance().getReader();
var eidCard = reader.getEIDCard();
var id = eidCard.getID();
pt.portugal.eid.PTEID_ReaderSet.releaseSDK();

```

Exception has occurred: CLR/System.TypeInitializationException
An unhandled exception of type 'System.TypeInitializationException' occurred in pteidlib_dotnet8+.dll: 'The type initializer for 'pt.portugal.eid.pteidlib_dotNetPINVOKE' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.DllNotFoundException : Unable to load shared library 'pteidlibCS_Wrapper' or one of its dependencies.

**Comment by ruiteixeira1** [comment]
Boa tarde,

A dll dotnet está a tentar carregar a dylib pteidlibCS_Wrapper, no entanto a dylib necessária chama-se pteidlib_dotnet8+.dylib.
Foi feita uma tentativa anterior de gerar um sdk? 
Deveria tentar carregar a dylib pteidlib_dotnet8+.dylib que é encontrada na mesma pasta que pteidlib_dotnet8+.dll, no caminho
"/usr/local/lib/"
Sugiro fazer uma limpeza das dlls na pasta /usr/local/lib/ e reinstalar a aplicação e repetir o teste.
Outra coisa como é que está a adicionar a dll no projeto dotnet?

Cumprimentos,

**Comment by snufffgit** [comment]
> Boa tarde,
> 
> A dll dotnet está a tentar carregar a dylib pteidlibCS_Wrapper, no entanto a dylib necessária chama-se pteidlib_dotnet8+.dylib. Foi feita uma tentativa anterior de gerar um sdk? Deveria tentar carregar a dylib pteidlib_dotnet8+.dylib que é encontrada na mesma pasta que pteidlib_dotnet8+.dll, no caminho "/usr/local/lib/" Sugiro fazer uma limpeza das dlls na pasta /usr/local/lib/ e reinstalar a aplicação e repetir o teste. Outra coisa como é que está a adicionar a dll no projeto dotnet?
> 
> Cumprimentos,

fiz referencia à dll <HintPath>/usr/local/lib/pteidlib_dotnet8/arm64/pteidlib_dotnet8+.dll</HintPath> e ficou a funcionar.

Obrigado.
