### ISSUE TITLE
Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11

### ISSUE THREAD

**Issue by macarao9876** [amagovpt/autenticacao.gov#192]
Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 qual a razão ?

**Comment by ruiteixeira1** [comment]
Boa tarde,

Que API é usada na leitura do cartão de cidadão?
De momento não damos suporte para aplicações em Delphi mas vamos tentar responder.

**Comment by macarao9876** [comment]
Boa tarde,

Criamos um Wrapper em C++ para ligar pteidlib_dotnet.dll ao Delphi ***@***.***

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: ruiteixeira1 ***@***.***>
Enviado: Wednesday, December 4, 2024 2:26:20 PM
Para: amagovpt/autenticacao.gov ***@***.***>
Cc: macarao9876 ***@***.***>; Author ***@***.***>
Assunto: Re: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)


Boa tarde,

Que API é usada na leitura do cartão de cidadão?
De momento não damos suporte para aplicações em Delphi mas vamos tentar responder.

**Comment by macarao9876** [comment]
Boa tarde,

A API foi API de Carregamento Dinâmico do Windows

Essa API permite carregar e chamar funções de uma DLL em tempo de execução. Aqui estão os principais componentes dessa API:

  1.  LoadLibrary: Carrega a DLL no processo atual.
  2.  GetProcAddress: Obtém o endereço de uma função exportada pela DLL.
  3.  FreeLibrary: Libera a DLL carregada.


Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: ruiteixeira1 ***@***.***>
Enviado: Wednesday, December 4, 2024 2:26:20 PM
Para: amagovpt/autenticacao.gov ***@***.***>
Cc: macarao9876 ***@***.***>; Author ***@***.***>
Assunto: Re: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)


Boa tarde,

Que API é usada na leitura do cartão de cidadão?
De momento não damos suporte para aplicações em Delphi mas vamos tentar responder.

**Comment by ruiteixeira1** [comment]
Boa tarde,

Que API do middleware é usada para ler a informação do cartão? A leitura é parcial de que forma? É possivel ler que partes e que partes não é possivel ler?

**Comment by macarao9876** [comment]
Bom dia.

Que API do middleware é usada para ler a informação do cartão?
Não sei se estarei a entender a V. questão.
De qualquer forma vou procurar responder.
No disco local temos instalada a aplicao.gov ("C:\Program Files\Portugal Identity Card\pteidguiV2.exe")
API de Atributos: Fornece acesso a atributos certificados, como nome, data de nascimento, e outros dados pessoais.

Quanto à questão: "A leitura é parcial de que forma?"
Cada função vai buscar o valor de cada campo. Ex:
3 exemplo a funcionar:

 iSzOfBuf := SizeOf(buffer);
  try
   // Ir buscar o Primeiro Nome/FirstName
   FillChar(buffer, 1025 , 0);
   FuncResult:= EId_GetGivenName(buffer, 1024);
   FirstName := AnsiString(buffer);
  except
      on E: Exception do
      begin
        ShowMessage('Erro: ' + E.Message);
        Exit;
      end;
  end;

 // Ir buscar o Apelido/LastName
  FillChar(buffer, iSzOfBuf, 0);
  EId_GetSurname(buffer, iSzOfBuf) ;
  LastName := AnsiString(buffer);

  FrmEidReader.edt1.Text := FirstName +'  '+ LastName ;

 // Ir buscar a Versão do Documento/DocumentVersion
  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetDocumentVersion(buffer, 1024);
  sGetDocumentVersion :='Ver Doc.: '+ AnsiString(buffer);

// Ir buscar o Tipo de Documento/DocumentType
  buffer[0] := #0;
  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetDocumentType(buffer, 1024);
  sDocumentType := AnsiString(buffer);

Etc......

  //BOF=================== funcoes em Cpp  que traz os dados acima referidos ========

int __declspec(dllexport) __stdcall EId_GetGivenName(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ givenName = Wrapper::eid->getGivenName();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(givenName);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetSurname(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ surname = Wrapper::eid->getSurname();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(surname);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetDocumentType(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ documentType = Wrapper::eid->getDocumentType();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(documentType);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

  //EOF================== funcoes em Cpp =============================

# exemplo de chamada que  funcionam caso  o "user" seja administrados (ou em alternativa se use "RunAsRob", salvo melhor,
não será solução); mas se não for administrador já não no utilizador "NÃO ADMINISTRADOR":
Há a chamada às funções, mas caso não seja o Administrador ou RunAsRob não retorna valores nem erro. Só que nada aparece.
FillChar(buffer, iSzOfBuf, 0);
  FillChar(buffer, SizeOf(buffer), 0);
  FuncResult := EId_GetAccidentalIndications(buffer, 1024);
  // WriteLn('GetAccidentalIndications Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');


  FillChar(buffer, iSzOfBuf, 0);
  FillChar(buffer, SizeOf(buffer), 0);
  FuncResult := EId_GetNationality(buffer, 1024);
   sNationality := AnsiString(buffer)  ;
  //WriteLn('GetNationality Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');


  FillChar(buffer, iSzOfBuf, 0);
  FillChar(buffer, SizeOf(buffer), 0);
  FuncResult := EId_GetCountry(buffer, 1024);
  sCountry := AnsiString(buffer);


  //WriteLn('GetCountry Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');
 // (*

  FillChar(buffer, iSzOfBuf, 0);
  FillChar(buffer, SizeOf(buffer), 0);
  FuncResult := EId_GetDateOfBirth(buffer, 1024);
  sDateOfBirth:=AnsiString(buffer);

  sDateOfBirth:= Copy(sDateOfBirth,1,2)+'/'+Copy(sDateOfBirth,4,2)+'/'+Copy(sDateOfBirth,7,4);
  DT:= StrToDate(sDateOfBirth);
  sDateOfBirth:=FormatDateTime( 'yyyy-mm-dd', dt );
  FrmEidReader.edt010.Text := 'Nacionalidade: '+ sNationality +' País: ' +sCountry +' Nasc. em:' + sDateOfBirth;
 // ShowMessage( 'Nacionalidade: '+ sNationality +' País: ' +sCountry +' Nasc. em:' + sDateOfBirth);
  // WriteLn('GetDateOfBirth Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');


  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetHeight(buffer, 1024);
  sHeight :=AnsiString(Buffer);


 //  WriteLn('GetHeight Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');


  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetGender(buffer, 1024);
  sGender:= AnsiString(buffer);

  //WriteLn('GetGender Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');

  FrmEidReader.edt011.Text := 'Altura: ' +sHeight +' Género: '+ sGender ;

  // ShowMessage('Altura: ' +sHeight +' Género: '+ sGender);


  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetMRZ1(buffer, 1024);
  // WriteLn('GetMRZ1 Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');
  sMRZ1:= AnsiString(buffer);

  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetMRZ2(buffer, 1024);
  sMRZ2 :=AnsiString(buffer);
  //  WriteLn('GetMRZ2 Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');


  FillChar(buffer, iSzOfBuf, 0);
  FuncResult := EId_GetMRZ3(buffer, 1024);
  sMRZ3:=  AnsiString(buffer);
  //  WriteLn('GetMRZ3 Result: ' + AnsiString(buffer) + ' (Function Result: ' + IntToStr(FuncResult) + ')');
  FrmEidReader.edt012.Text := 'Mrz 1: '+ sMRZ1 +' Mrz 2: '+sMRZ2+ ' MRZ 3: '+ sMRZ3 ;

  // ShowMessage('Mrz 1: '+ sMRZ1 +' Mrz 2: '+sMRZ2+ ' MRZ 3: '+ sMRZ3);


  //BOF====================== funcoes em Cpp =============================

int __declspec(dllexport) __stdcall EId_GetAccidentalIndications(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ accidentalIndications = Wrapper::eid->getAccidentalIndications();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(accidentalIndications);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetNationality(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ nationality = Wrapper::eid->getNationality();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(nationality);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetCountry(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ country = Wrapper::eid->getCountry();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(country);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetDateOfBirth(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ dateOfBirth = Wrapper::eid->getDateOfBirth();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(dateOfBirth);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetHeight(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ height = Wrapper::eid->getHeight();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(height);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetGender(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ gender = Wrapper::eid->getGender();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(gender);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetMRZ1(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ mrz = Wrapper::eid->getMRZ1();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(mrz);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetMRZ2(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ mrz = Wrapper::eid->getMRZ2();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(mrz);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

int __declspec(dllexport) __stdcall EId_GetMRZ3(char* buffer, int bufferLength)
{
    if (initialized)
    {
        try
        {
            Wrapper::exception_name = gcnew String("");
            Wrapper::exception_message = gcnew String("");
            Wrapper::exception_stack_trace = gcnew String("");

            System::String^ mrz = Wrapper::eid->getMRZ3();

            System::IntPtr p = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(mrz);
            char* pNewCharStr = static_cast<char*>(p.ToPointer());
            lstrcpynA(buffer, pNewCharStr, bufferLength);
            System::Runtime::InteropServices::Marshal::FreeHGlobal(p);
            return 0;
        }
        catch (Exception^ ex)
        {
            Wrapper::exception_name = ex->GetType()->Name;
            Wrapper::exception_message = ex->Message;
            Wrapper::exception_stack_trace = ex->StackTrace;
            return -1;
        }
    }
    else
        return -100;
}

  //EOF====================== funcoes em Cpp =============================


Ex:
Nacionalidade: PRT
País: PRT
Nasc. em:1979-07-02

Mrz 1: I<PRT114654034<ZX51<<<<<<<<<<<
Mrz 2: 7907027M3106143PRT<<<<<<<<<<<8
MRZ 3: CORREIA<DA<FONSECA<<ANDRE<<<<<

Altura: 1,76
Género: M


Quanto à Vossa questão: "É possível ler que partes e que partes não é possível ler?"
Na imagem em anexo tem os campos pintados de amarelo que não consegue ler enquanto utilizador padrão (não administrador).
Todo o resto, pintado a verde, é possível ler, independentemente do utilizador ser ou não ser Administrador!
Convenhamos que é um comportamento estranho para uma API, até porque, salvo melhor, e com o devido respeito, os dados que se não conseguem ler não são dados sensíveis ou pelo menos não serão mais sensíveis que aqueles que se conseguem ler. Obrigado
Na expectativa das Vossas notícias, subscrevo-me
Atentamente




________________________________
De: ruiteixeira1 ***@***.***>
Enviado: 4 de dezembro de 2024 16:47
Para: amagovpt/autenticacao.gov ***@***.***>
Cc: macarao9876 ***@***.***>; Author ***@***.***>
Assunto: Re: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)


Boa tarde,

Que API do middleware é usada para ler a informação do cartão? A leitura é parcial de que forma? É possivel ler que partes e que partes não é possivel ler?

**Comment by ruiteixeira1** [comment]
Boa tarde,

Eu quero entender como o projeto está a chamar a API que disponibilizamos, pelo que vi parece estar dentro desse namespace "Wrapper".

Esse wrapper parece ocultar certas chamadas á API necessárias, como obter o cartão como getEIDCard() e getID() para obter a informação do cartão como a nacionalidade e etc. Pode mostrar um pouco mais sobre como esse wrapper chama essas funções? Estou a assumir que usa a API em c++, existe também uma API mais legado que é apenas C.

Sobre a imagem em anexo, eu não consigo vê-la, imagens enviadas por email não aparecem nos issues do github, pode enviar novamente de outra forma? Obrigado.

**Comment by macarao9876** [comment]
[cid:259dfd60-a44c-49e7-b21a-7a310ae3d022]
________________________________
De: ruiteixeira1 ***@***.***>
Enviado: 5 de dezembro de 2024 16:32
Para: amagovpt/autenticacao.gov ***@***.***>
Cc: macarao9876 ***@***.***>; Author ***@***.***>
Assunto: Re: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)


Boa tarde,

Eu quero entender como o projeto está a chamar a API que disponibilizamos, pelo que vi parece estar dentro desse namespace "Wrapper".

Esse wrapper parece ocultar certas chamadas á API necessárias, como obter o cartão como getEIDCard() e getID() para obter a informação do cartão como a nacionalidade e etc. Pode mostrar um pouco mais sobre como esse wrapper chama essas funções? Estou a assumir que usa a API em c++, existe também uma API mais legado que é apenas C.

Sobre a imagem em anexo, eu não consigo vê-la, imagens enviadas por email não aparecem nos issues do github, pode enviar novamente de outra forma? Obrigado.

**Comment by macarao9876** [comment]
Sobre a imagem em anexo, eu não consigo vê-la, imagens enviadas por email não aparecem nos issues do github, pode enviar novamente de outra forma?

como sugere que faça isso ?
________________________________
De: André Fonseca ***@***.***>
Enviado: 6 de dezembro de 2024 16:01
Para: amagovpt/autenticacao.gov ***@***.***>
Assunto: RE: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)

[cid:259dfd60-a44c-49e7-b21a-7a310ae3d022]
________________________________
De: ruiteixeira1 ***@***.***>
Enviado: 5 de dezembro de 2024 16:32
Para: amagovpt/autenticacao.gov ***@***.***>
Cc: macarao9876 ***@***.***>; Author ***@***.***>
Assunto: Re: [amagovpt/autenticacao.gov] Consigo ler o cartão de cidadão numa aplicação feita em Delphi como administrador mas só parcialmente como utilizador padrão do Windows 11 (Issue #192)


Boa tarde,

Eu quero entender como o projeto está a chamar a API que disponibilizamos, pelo que vi parece estar dentro desse namespace "Wrapper".

Esse wrapper parece ocultar certas chamadas á API necessárias, como obter o cartão como getEIDCard() e getID() para obter a informação do cartão como a nacionalidade e etc. Pode mostrar um pouco mais sobre como esse wrapper chama essas funções? Estou a assumir que usa a API em c++, existe também uma API mais legado que é apenas C.

Sobre a imagem em anexo, eu não consigo vê-la, imagens enviadas por email não aparecem nos issues do github, pode enviar novamente de outra forma? Obrigado.

**Comment by macarao9876** [comment]
são dados sensiveis e não quero que fiquem abertos ao publico

**Comment by macarao9876** [comment]
Quem é V. Exª.? Fala em nome da AMA? Posso conhecer as suas credenciais?
