### ISSUE TITLE
Erro no carregamento da pteidlib versão 3.0.19 (SDK Java, dotnet e C++ em Windows e MacOS) 

### ISSUE THREAD

**Issue by ACamposPT** [amagovpt/autenticacao.gov#2]
A versão 3.0.19 da pteidlib (SDK Java, dotnet e C++) tem dependências extra que não estão a ser adicionadas pelo instalador x64, nos casos em que o sistema operativo Windows é x64 mas a aplicação está utilizar o SDK x86 (32-bits).

**Comment by ACamposPT** [comment]
Para resolver este problema no imediato, criamos um zip, que contêm 3 ficheiros dll. Pedimos para colocarem esses dll's na pasta do executável da aplicação que usa o SDK.

Link para download:
https://drive.google.com/drive/folders/1XkQ7tunA0l2YyeGlygwigM0DrQFirCdn?usp=sharing

Estamos a trabalhar para o resolver o problema da melhor forma na próxima release.

**Comment by agrr** [comment]
Em MacOS temos um efeito do mesmo issue no carregamento do SDK Java (3.0.20): 

`
Native code library failed to load. 
java.lang.UnsatisfiedLinkError: /usr/local/lib/libpteidlibj.2.0.0.dylib: dlopen(/usr/local/lib/libpteidlibj.2.0.0.dylib, 1): Library not loaded: @rpath/QtGui.framework/Versions/5/QtGui
  Referenced from: /usr/local/lib/libpteidapplayer.2.0.0.dylib
  Reason: image not found
`

Um workaround possível em ambiente de desenvolvimento para a versão actualmente disponível (3.0.20) é o seguinte comando que exige a presença no sistema das "Command Line Tools for XCode":
 
```
sudo install_name_tool -rpath /Users/yosemite/Qt5.9/5.9.2/clang_64/lib /Applications/Autenticação.gov.app/Contents/Frameworks/ /usr/local/lib/libpteidapplayer.2.dylib
```

**Comment by ACamposPT** [comment]
Issue resolvido na Release v3.0.21

**Comment by agrr** [comment]
Mantém-se aberto o issue relativo ao MacOS até à Release 3.0.21

**Comment by ACamposPT** [comment]
Issue resolvido na Release v3.1.0
