### ISSUE TITLE
Compilação falha com invalid conversion from ‘const X509_CRL*’

### ISSUE THREAD

**Issue by jbbandos** [amagovpt/autenticacao.gov#20]
Estou a tentar compilar no MX Linux 19, que é baseado em debian. Instalei as dependências como se fosse para o ubuntu 18, com a diferença única que em vez de libssl1.0-dev utilizei libssl-dev. O libssl disponível nesta versão do MX linux é o 1.1.1d-0+deb10u2. Talvez por isso, a compilação agora falha no cryptoFramework.cpp. O primeiro erro que tenho é:
`cryptoFramework.cpp:306:51: error: invalid conversion from ‘const X509_CRL*’ {aka ‘const X509_crl_st*’} to ‘X509_CRL*’ {aka ‘X509_crl_st*’} [-fpermissive]
  if(X509_cmp_current_time(X509_CRL_get_lastUpdate(pX509_Crl))<=0`
Incluo o output da compilação.
[compile.log](https://github.com/amagovpt/autenticacao.gov/files/4468692/compile.log)

**Comment by agrr** [comment]
Viva,

para suportar a compilação com OpenSSL 1.1 é preciso compilar o branch `openssl-migration`.

O branch master assume que estamos a utilizar ainda a libssl 1.0.2

**Comment by jbbandos** [comment]
Obrigado. Agora falha por não ter instalado o openjdk, vou abrir outro issue para isso.
