### ISSUE TITLE
branch openssl-migration - falta dependência de openjdk-11-jdk

### ISSUE THREAD

**Issue by jbbandos** [amagovpt/autenticacao.gov#21]
Quando se tenta compilar a branch openssl-migration, falha com:
`
g++ -c -pipe -fPIC -fno-strict-aliasing -O2 -std=gnu++11 -fPIC -DPTEID_35 -DEIDMW_PREFIX=/usr/local -DEIDMW_CMN_EXPORT -DEIDMW_EIDLIB_EXPORTS -I. -I. -I../applayer -I../dialogs -I../common -I../cardlayer -I../eidlib -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -isystem /usr/include/PCSC -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o eidlibJava_Wrapper.o GeneratedFiles/eidlibJava_Wrapper.cpp
GeneratedFiles/eidlibJava_Wrapper.cpp:178:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:554: eidlibJava_Wrapper.o] Error 1
make[1]: Leaving directory '/media/other/filmes/externo/WIP/CC/autenticacao.gov/pteid-mw-pt/_src/eidmw/eidlibJava_Wrapper'
make: *** [Makefile:399: sub-eidlibJava_Wrapper-make_first-ordered] Error 2
`

Instalando openjdk-11-jdk resolve o problema.

**Comment by agrr** [comment]
Aqui é uma questão de atualizar a lista de dependências no branch openssl-migration.
Obrigado pelo feedback

**Comment by marado** [comment]
A actualização do README não é suficiente: há também, pelo menos, que actualizar o debian/control .

**Comment by agrr** [comment]
O debian/control no branch `openssl-migration` já está actualizado: 

https://github.com/amagovpt/autenticacao.gov/blob/openssl-migration/pteid-mw-pt/_src/eidmw/debian/control
