### ISSUE TITLE
Suporte para Ubuntu 20.04

### ISSUE THREAD

**Issue by tiago-as** [amagovpt/autenticacao.gov#22]
Ao tentar instalar o Software do Cartão de Cidadão criado para Ubuntu 19.10 em Uubuntu 20.04 há uma dependência que não é possível de satisfazer: o pacote qtbase-abi-5-12-4 não existe nos repositórios. No entanto existe uma versão mais recente do mesmo pacote. Visto que este pacote se trata de um pacote virtual, suponho que apenas basta alterar a dependência para que seja possível instalar o software na versão mais recente do sistema operativo.

Seria possível criarem um .deb para a versão 20.04?

A médio prazo, poderia ser interessante gerir as diferentes versões através de um PPA.

Muito obrigado

**Comment by agrr** [comment]
Foi hoje lançado oficialmente o Ubuntu 20.04 e como tal vamos disponibilizar muito brevemente o .deb compatível. 
Terá também uma alteração que impederá que uma diferença de minor version como esta 5.12.4 -> 5.12.8 quebre a compatibilidade do pacote no futuro.

**Comment by agrr** [comment]
Já foi disponibilizada a versão 3.1.0 oficial para Ubuntu 20.04
