### ISSUE TITLE
Build do projeto em Windows (10)

### ISSUE THREAD

**Issue by cristiano2lopes** [amagovpt/autenticacao.gov#23]
Estou a tentar fazer build do projeto em Windows e estou com algumas dúvidas. A documentação é bastante boa mas alguns pontos não estão claros para mim e se me pudessem ajudar ficaria imensamente agradecido.

1. Existe algum sítio onde possa ver que **versões e opções de build** devo utilizar para cada uma das dependências no ficheiro [set_path_autenticacao.gov.bat](https://github.com/amagovpt/autenticacao.gov/blob/master/pteid-mw-pt/windows/set_path_autenticacao.gov.bat) ?
2. O ficheiro Credentials.h só deve ser modificado se estivermos a fazer build para Chave Móvel Digital ?
3. O [script](https://github.com/amagovpt/autenticacao.gov/blob/master/pteid-mw-pt/windows/ezbuild_sln_autenticacao.gov.bat) deixa o projeto com todas as dependência configuradas, de acordo com o definido no set_path_autenticacao.gov.bat ?

Se me pudessem facultar um zip com a hipotética folder/pasta `C:\git\tools\build-scripts\windows\external-libs` isso responderia a quase todas as minhas perguntas. Outra possibilidade seria um script de aprovisionamento de maquina virtual (Vagrant por exemplo) embora calcule que o vosso tempo não deve abundar e o zip talvez seja uma opção mais simples/menos consumidora de tempo. 

Desde já o meu obrigado por todo o vosso trabalho,
Cristiano Lopes

**Comment by ACamposPT** [comment]
As nossa respostas:
1) Actualizamos hoje as instruções para compilação em Windows (Visual Studio 2013) no READ.ME, com a indicação das versões que estamos a usar de todas as dependências.
2) Sim. Não é necessário modificar o ficheiro, ficando a aplicação sem suporte para a Chave Móvel Digital.
3) Sim. Deve configurar o ficheiro "set_path_autenticacao.gov.bat" com o caminho para todas as dependências. Nós não distribuímos as dependências pré-compiladas. Qualquer duvida ou questão na compilação de algumas das dependências, não hesite em contactar novamente.

Obrigado.

**Comment by cristiano2lopes** [comment]
@ACamposPT Obrigado pela resposta. Enviei o PR #25 que documenta o meu processo até conseguir fazer build com sucesso, que espero tenha alguma utilidade para vocês e restante comunidade.
