### ISSUE TITLE
Distribuições Linux não oficias - Aplicação Instalada não possui suporte para o serviço de Chave Móvel Digital

### ISSUE THREAD

**Issue by dfdias** [amagovpt/autenticacao.gov#24]
Estou a correr ArchLinux. Instalei o pacote que é fornecido em 
https://aur.archlinux.org/packages/autenticacao-gov-pt/
Funciona tudo bem. no entanto quando tento assinar com chave móvel diz-me que a aplicação não possui suporte para isso. Esta é uma limitação da build que eles fornecem ou é uma limitação imposta para linux ?

**Comment by ACamposPT** [comment]
Boa tarde,
O MW autenticacao.gov é disponibilizado oficialmente para vários sistemas, nomeadamente as seguintes distribuições linux: Ubuntu, Fedora e OpenSuse. Os pacotes distribuições têm suporte para a Chave Móvel Digital. 

A lista completa pode ser verificada no seguinte link:
https://www.autenticacao.gov.pt/cc-software

O pacote para ARCH que refere é da responsabilidade dos seus criadores, deve entrar em contacto com eles. Eles poderão adicionar suporte para a Chave Móvel Digital, mas para isso terão de contactar a AMA e seguir os procedimentos indicados.

**Comment by marado** [comment]
@ACamposPT : Quer isto dizer que o suporte para a Chave Móvel Digital não é software livre e não está disponível para quem quiser fazer build dos seus próprios pacotes (ou outras distribuições que queiram suportar essa funcionalidade)?

Se for esse o caso, podem por favor essa informação na documentação?

Se não é esse o caso, podem explicar melhor a necessidade que um packager terá em "ter de contactar a AMA", e o objectivo desses "procedimentos indicados"?

**Comment by a36233** [comment]
> Estou a correr ArchLinux. Instalei o pacote que é fornecido em
> https://aur.archlinux.org/packages/autenticacao-gov-pt/
> Funciona tudo bem. no entanto quando tento assinar com chave móvel diz-me que a aplicação não possui suporte para isso. Esta é uma limitação da build que eles fornecem ou é uma limitação imposta para linux ?

Em ArchLinux com o pacote https://aur.archlinux.org/packages/autenticacao-gov-pt-bin/ a assinatura via CMD funciona verifica que tens a assinatura digital via CMD activada caso contrário deve aparecer-te o seguinte erro:
![Screenshot_2020-05-07_22-02-44](https://user-images.githubusercontent.com/4481169/81347850-ddec8600-90b4-11ea-9341-998eaf2085a2.png)

https://www.autenticacao.gov.pt/web/guest/area-privada/chave-movel-digital

Em relação ao pacote https://aur.archlinux.org/packages/autenticacao-gov-pt/ este é compilado usando o source code e sem as devidas credenciais para assinar o módulo o CMD não funciona.
![Screenshot_2020-05-07_22-59-02](https://user-images.githubusercontent.com/4481169/81348872-d201c380-90b6-11ea-9669-eacbc7bc1a61.png)

**Comment by ACamposPT** [comment]
As distribuições Linux não oficias, criadas pelas respectivas comunidades, podem não ter suporte para usar a CMD.

O serviço server-side da Chave Móvel Digital, requer credenciais. Devem contactar os responsáveis pela criação dos pacotes da distribuição e eles por sua vez devem contactar a AMA pelo email info.cidadao@ama.pt
