### ISSUE TITLE
Actualização da aplicação não é executada em Ubuntu 18.04

### ISSUE THREAD

**Issue by tcarrondo** [amagovpt/autenticacao.gov#27]
Ao tentar aceder aos ddos do meu CC deparei-me com o erro: "consistência do cartão está comprometida" não conseguindo aceder aos dados nem assinar documentos.

Tentei, através da aplicação (v3.0.16), fazer a actualização para a versão mais recente encontrada (v3.0.21), mas sem sucesso.

O que verifiquei:
* A barra de progressão da transferência chega ao fim, mas depois nada acontece;
* A transferência ocorre (o ficheiro pteid-mw_ubuntu18_amd64.deb fica na pasta /tmp);
* O ficheiro transferido é da versão: 3.0.20+git20190930-e547bd9d-1;
* Consegui instalar manualmente o deb;
* Com esta versão já consegui aceder e assinar um documento;
* No site https://www.autenticacao.gov.pt/web/guest/aplicacao/aplicacao-autenticacao-gov já só está disponível para download a versão para Ubuntu 20.04, que é incompatível com Ubuntu 18.04;
* A versão 3.0.20 também não consegue fazer actualização através ada opção da aplicação deste vez com o erro: "Por favor verifique a sua ligação a internet e volte a tentar."

Uma versão snap resolvia todas estas questões de uma só vez.

**Comment by ACamposPT** [comment]
As actualizações automáticas da aplicação estão temporariamente indisponíveis. Esta a ser feita uma remodelação do portal "Autenticação.gov". Tentaremos resolver o problema o mais rápido possível. Obrigado.

Ubuntu 18:
https://www.autenticacao.gov.pt/documents/20126/78595/Autenticacao.gov_Ubuntu_20_x64.deb
Ubuntu 18:
https://www.autenticacao.gov.pt/documents/20126/78595/Autenticacao.gov_Ubuntu_20_x64.deb
Ubuntu 18:
https://www.autenticacao.gov.pt/documents/20126/78595/Autenticacao.gov_Ubuntu_20_x64.deb

**Comment by tcarrondo** [comment]
Enquanto isso não acontece é possível disponibilizar o(s) .deb compatíveis com a versão 18.04?

**Comment by ACamposPT** [comment]
A ultima versão disponibilizada para Ubuntu 18 é que já tem, a 3.0.20. Pode ver aqui a lista de releases e os detalhes das mesmas:

https://github.com/amagovpt/autenticacao.gov/releases

As versões superiores não têm nenhuma funcionalidade adicional para Linux ou correcção que justifique uma nova Release para Ubuntu18, pelo menos por enquanto.

**Comment by agrr** [comment]
Apesar de ainda não terem sido repostos os links na página de download estão disponíveis os pacotes oficiais nos seguintes URLs:

Ubuntu 18.04 -
https://www.autenticacao.gov.pt/documents/20126/78595/Autenticacao.gov_Ubuntu_18_x64.deb

Ubuntu 19.10 -
https://www.autenticacao.gov.pt/documents/20126/78595/Autenticacao.gov_Ubuntu_19_x64.deb

**Comment by ACamposPT** [comment]
Os links para Ubuntu 18 e 19 já foram repostos.

https://www.autenticacao.gov.pt/web/guest/cc-aplicacao

**Comment by tcarrondo** [comment]
obrigado a ambos, @agrr @ACamposPT
