### ISSUE TITLE
ERROR: SSLConnection: error establishing connection.

### ISSUE THREAD

**Issue by josepostiga** [amagovpt/autenticacao.gov#29]
Olá a todos.

Estou a tentar efetuar a confirmação de alteração de morada mas dá-me sempre erro após inserir os dados pedidos, corretamente.

O output apresentado no ficheiro de log .PTEID_0.log é:

```
/usr/local/bin/eidguiV2 - 2020-05-19 16:54:37 - 52440|140258211505920 - applayer - ERROR: SSLConnection: error establishing connection. Detail: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
/usr/local/bin/eidguiV2 - 2020-05-19 16:54:37 - 52440|140258211505920 - eidgui - ERROR: Caught exception in EidCard.ChangeAddress()... closing progressBar
/usr/local/bin/eidguiV2 - 2020-05-19 16:54:37 - 52440|140258905660032 - eidgui - ERROR: AddressChange op finished with error code 0xe1d01d04
```

Se precisarem de mais algum detalhe para ajudar a despistar o problema, digam.

Obrigado.

**Comment by ACamposPT** [comment]
Boa tarde,
Coloque a aplicação em modo DEBUG e tente novamente. Em seguida, envie o ficheiro log completo. Se preferir pode contactar o suporte pelo email indicado na mensagem de erro, mas deve ser enviar o ficheiro log completo.
Obrigado

**Comment by josepostiga** [comment]
@ACamposPT aqui fica o log completo. Tentei novamente, mas obtive o mesmo erro.

[PTEID_0.log](https://github.com/amagovpt/autenticacao.gov/files/4655196/PTEID_0.log)

**Comment by ACamposPT** [comment]
A versão em produção 3.1.0 para Ubuntu 20.04 não está funcional para efectuar a alteração de morada. Estamos a efectuar a correcção e vamos disponibilizar uma nova versão nos próximos dias.

Entretanto, se possível, poderá efectuar com as outras versões.

No entanto se optar pelas versões Ubuntu18 ou Ubuntu19, deverá ter em conta o seguinte (especialmente os 2 últimos comentários):

https://github.com/amagovpt/autenticacao.gov/issues/27

**Comment by agrr** [comment]
Já disponível a release 3.1.1 para Ubuntu 20 que corrige este issue.
