### ISSUE TITLE
Erro em debian 10..

### ISSUE THREAD

**Issue by FlPCrZ** [amagovpt/autenticacao.gov#31]
OS: debian 10 (buster)
Erro: "./eidguiV2/eidguiV2: error while loading shared libraries: libpteidcommon.so.2: cannot open shared object file: No such file or directory".

O que tentei:
1) export LD_LIBRARY_PATH=$(pwd)/libs
2) ln -s lib/libpteidcommon.so.2 /usr/local/lib/
3) mkdir /usr/local/include && ln -s lib/libpteidcommon.so.2 /usr/local/include/
...
Isto depois de tentar os *.deb... Ate os msi com wine tentei!!!! Nadinha! 

Nao sei se existe a versao cli? Assim poderia usar docker para o build?
Qualquer ajuda, agradeco desde ja!

**Comment by agrr** [comment]
Viva,

executar a aplicação directamente a partir da directoria de build não vai funcionar num "ambiente limpo" onde nunca tenha sido instalado o software.

É preciso instalar com `make install`, actualizar a cache do dynamic loader com `ldconfig`
e nesse momento já podemos executar a aplicação em:

`/usr/local/bin/eidguiV2`

**Comment by FlPCrZ** [comment]
Obrigado pela resposta rapida.
Fico agora bloqueado com o seguinte erro:
C++: Using application scaling.
C++: Application scaling:  1
C++: AppController started. App version:  "3.1.2 - 3831 [ 04873c4c ]"
C++: currentCpuArchitecture(): "x86_64"
C++: prettyProductName(): "Debian GNU/Linux 10 (buster)"
C++: Starting App with graphics acceleration
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
C++: GAPI LoadTranslationFile "eidmw_nl" "/usr/local/bin"
C++: AppController LoadTranslationFile "eidmw_nl" "/usr/local/bin"
QQmlApplicationEngine failed to load component
qrc:/main.qml:13 module "QtQuick" is not installed
qrc:/main.qml:17 module "QtQuick.Window" is not installed
qrc:/main.qml:13 module "QtQuick" is not installed
qrc:/main.qml:17 module "QtQuick.Window" is not installed

As dependencias indicadas foram instaladas..

**Comment by agrr** [comment]
Deverão faltar módulos qml que são fornecidos pelos pacotes indicados no campo "Depends:" do ficheiro debian/control:

https://github.com/amagovpt/autenticacao.gov/blob/master/pteid-mw-pt/_src/eidmw/debian/control

**Comment by FlPCrZ** [comment]
Boas,
Problema resolvido.. Obrigado!
Uma actualizacao da documentacao teria provavelmente evitado isto..

"Instalar dependencias"
`
sudo apt install libpcsclite-dev libpoppler-qt5-dev libzip-dev libopenjp2-7-dev libpng-dev openjdk-11-jdk qtbase5-dev qt5-qmake qtbase5-private-dev qt5-default qtdeclarative5-dev qtquickcontrols2-5-dev libssl-dev libxerces-c-dev libxml-security-c-dev swig libcurl4-nss-dev libnsspem pcscd qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-layouts qml-module-qtquick2 qml-module-qtquick-window2  libnsspem qt5-gtk-platformtheme qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qt-labs-platform
`

"Clonar repositorio"
`git clone <REPOSITORIO>`

"Build"
`
cd pteid-mw-pt/_src/eidmw
qmake pteid-mw.pro
make
sudo make install
sudo ldconfig
`
"Lancar a aplicacao"
`eidguiV2`
