### ISSUE TITLE
Assinatura digital via CMD não reconhecida como válida no site DSS

### ISSUE THREAD

**Issue by indicum** [amagovpt/autenticacao.gov#33]
Ola,

No site DSS da UE, a assinatura digital efectuada via CMD não é reconhecida como valida (a versão actual é a 5.6 mas dizem que vão actualizar para versão 5.7)
https://ec.europa.eu/cefdigital/DSS/webapp-demo/validation

Na versão anterior (5.5), acessível via https://joinup.ec.europa.eu/dss-webapp/validation, a assinatura é reconhecida.
A CMD esta a necessitar de uma actualização para estar a par das novas regras de segurança.

Como consequência desta falha a maioria dos TSP ja deixaram de reconhecer as assinaturas via CMD.
Não verifiquei, mas disseram que o mesmo esta a acontecer com as assinaturas via CC.

Razão dada é que é devido ao uso de encriptação SHA1 no certificado de revogação já que SHA1 já não é considerado um algoritmo seguro.
_DSS 5.6 rejects the signature because of SHA-1 being used as signature hash algorithm in the revocation information (OCSP). DSS 5.5. still allowed SHA-1 in OCSPs if I remember correctly_.

Mais detalhes no ticket aberto no site DSS: https://ec.europa.eu/cefdigital/tracker/browse/DSS-2097

Joaquim
[CMD-failure.zip](https://github.com/amagovpt/autenticacao.gov/files/4840799/CMD-failure.zip)

**Comment by agrr** [comment]
Boa tarde,

a entidade responsável pelo serviço OCSP do Cartão de Cidadão e Chave Móvel já foi informada deste issue e o mesmo está em processo de resolução.
