### ISSUE TITLE
Obtenção da morada sem validar o pin através do popup 

### ISSUE THREAD

**Issue by BernardoPoiares** [amagovpt/autenticacao.gov#34]
Boa tarde,

Eu estou a tentar utilizar dinamicamente a dll pteidlib.dll para obter os dados do cartão de cidadão, nomeadamente a morada. 
Nas versões anteriores da dll, a mesma permitia obter a morada sem aparecer o popup de verificação do pin se anteriormente fosse chamada a função PTEID_VerifyPIN e validado com sucesso o pin.
No entanto o mesmo já não acontece com as versões mais recentes.
Existe alguma possibilidade de validar o pin sem o aparecimento do popup?

**Comment by miguelblcfigueira** [comment]
Boa tarde,

Sim, existe essa possiblidade.
A função PTEID_VerifyPIN é de compatibilidade com o SDK antigo e deixou de suportar essa funcionalidade. Os novos métodos estão descritos no [manual do SDK](https://amagovpt.github.io/autenticacao.gov/manual_sdk.html#obten%c3%a7%c3%a3o-da-morada).

Para ler a morada sem aparecer o popup deve-se fazer da seguinte forma:

```cpp
(...)
PTEID_Pins pins = card.getPins();
PTEID_Pin pin = pins.getPinByPinRef(PTEID_Pin.ADDR_PIN);
if (pin.verifyPin("0000", &triesLeft)){
	PTEID_Address &addr =  card.getAddr();
	const char * municipio =  addr.getMunicipality();
        (...)
}
```

Atenção para a chamada ao método verifyPin: se o PIN for passado no primeiro argumento, o popup não irá aparecer (documentado [aqui](https://amagovpt.github.io/autenticacao.gov/sdk/cpp/classeIDMW_1_1PTEID__Pin.html#a607cdb3a73dd5784fab0ab86461de11c)).

Será adicionada uma nota ao manual do SDK sobre esta funcionalidade.
