### ISSUE TITLE
Pacotes disponibilizados para Linux desactualizados (<3.2.0)

### ISSUE THREAD

**Issue by tomaspinho** [amagovpt/autenticacao.gov#35]
Os pacotes disponibilizados da aplicação em https://www.autenticacao.gov.pt/cc-aplicacao estão desactualizados. Inclusivé, é activado o popup no arranque da aplicação com aviso que versões inferiores à `3.2.0` não permitem confirmar a alteração de morada, devido a certificados desactualizados.

Ao compilar a aplicação na versão mais recente, o código de erro apresentado ao tentar confirmar alteração de morada passa a ser igual ao apresentado nos restantes sistemas operativos (`1120`). Enviei e-mail para o apoio.

**Comment by ACamposPT** [comment]
Boa tarde,
A mensagem no popup é diferente, a mensagem diz "Versões da aplicação Autenticação.gov anteriores à versão 3.1.2 devem ser atualizadas devido à revogação de certificados, nomeadamente para conseguir assinar com Chave Móvel Digital e Atributos Profissionais." Pode existir aqui algum equivoco. Pedimos mais detalhes.

O código de erro 1120 na alteração de morada vem do serviço e quer dizer que não existe processo de Alteração de Morada para o cartão em causa. Nesses casos, deve mesmo contactar o suporte.

**Comment by tomaspinho** [comment]
Não sei se não me expressei correctamente. De facto ocorre esse erro, mas não é dependente da versão. Ao contrário do que acontecia anteriormente porque o erro era relativo a certificados na versão 3.1.1, a única disponibilizada para Ubuntu. A intenção da issue era que lançassem a versão com os novos certificados também para Linux.

**Comment by tomaspinho** [comment]
@ACamposPT foi-me possível alterar a morada no cartão usando uma build do `master` do repositório. No entanto, os pacotes disponibilizados para Linux continuam desactualizados aqui: https://www.autenticacao.gov.pt/cc-aplicacao

Vão lançar novos?
