### ISSUE TITLE
 plugin Autenticação.Gov

### ISSUE THREAD

**Issue by flippipe** [amagovpt/autenticacao.gov#37]
Bom dia,

Porque é que o plugin Autenticação.Gov não se encontra disponível de uma forma mais simples.
- Ou diretamente no site onde se encontra a [aplicação](https://www.autenticacao.gov.pt/cc-aplicacao) ;
- Ou embebido no deb da própria aplicação.

Comportamento verificado no Ubuntu 20.04 com o pacote Autenticacao.gov_Ubuntu_20_x64.deb

**Comment by ACamposPT** [comment]
Boa tarde,
As suas sugestões vão ser tidas em conta pela nossa equipa. obrigado. 

No entanto deixo aqui os links para o plugin e para a aplicação.

Plugin:
https://www.autenticacao.gov.pt/web/guest/cartao-cidadao/autenticacao

Aplicação:
https://www.autenticacao.gov.pt/web/guest/aplicacao/aplicacao-autenticacao-gov

**Comment by caracol78** [comment]
Boa tarde  não consigo acedder ao site quecolocou no link obrigado
