### ISSUE TITLE
Usar o plugin Autenticação.gov. em site

### ISSUE THREAD

**Issue by wedevel** [amagovpt/autenticacao.gov#4]
Não sei se me podem ajudar, já procurei em vários sítios mas não encontro esta informação.

No passado já cheguei a usar aplicações java para ler dados do cartão de cidadão, no entanto agora gostaria de integrar a leitura de alguns dados do cartão de cidadão num site usando o plugin Autenticação.gov.

Existe já algo disponível para podermos fazer esta integração, ou é necessário desenvolver na mesma?

Obrigado

**Comment by ACamposPT** [comment]
Boa tarde,
Este repositório é do Middleware Oficial do Cartão de Cidadão. O plugin Autenticação.gov é outro projecto desenvolvido por equipas diferentes. 

Deverá apresentar o pedido em info.cidadao@ama.pt

Obrigado.
