### ISSUE TITLE
Erro novos Cartão de Cidadão

### ISSUE THREAD

**Issue by stivencamara** [amagovpt/autenticacao.gov#41]
Tenho uma aplicação desenvolvida com o SDK 3.1.2, e ao tentar ler com os novos Cartão de Cidadão ocorre o erro abaixo.

{"ClassName":"System.TypeInitializationException","Message":"The type initializer for 'pt.portugal.eid.pteidlib_dotNetPINVOKE' threw an exception.","Data":null,"InnerException":{"ClassName":"System.TypeInitializationException","Message":"The type initializer for 'SWIGExceptionHelper' threw an exception.","Data":null,"InnerException":{"ClassName":"System.BadImageFormatException","Message":"Foi efetuada uma tentativa de carregar um programa com um formato incorreto. (Exception from HRESULT: 0x8007000B)","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at pt.portugal.eid.pteidlib_dotNetPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_pteidlib_dotNet(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)\r\n   at pt.portugal.eid.pteidlib_dotNetPINVOKE.SWIGExceptionHelper..cctor()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nSWIGRegisterExceptionCallbacks_pteidlib_dotNet\npteidlib_dotnet, Version=3.1.2.3925, Culture=neutral, PublicKeyToken=1fa91d379e36932f\npt.portugal.eid.pteidlib_dotNetPINVOKE+SWIGExceptionHelper\nVoid SWIGRegisterExceptionCallbacks_pteidlib_dotNet(ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate)","HResult":-2147024885,"Source":"pteidlib_dotnet","WatsonBuckets": [...]
,"BadImageFormat_FileName":null,"BadImageFormat_FusionLog":null},"HelpURL":null,"StackTraceString":"   at pt.portugal.eid.pteidlib_dotNetPINVOKE.SWIGExceptionHelper..ctor()\r\n   at pt.portugal.eid.pteidlib_dotNetPINVOKE..cctor()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\npteidlib_dotnet, Version=3.1.2.3925, Culture=neutral, PublicKeyToken=1fa91d379e36932f\npt.portugal.eid.pteidlib_dotNetPINVOKE+SWIGExceptionHelper\nVoid .ctor()","HResult":-2146233036,"Source":"pteidlib_dotnet","WatsonBuckets": [...]

Isso só está a acontecer com os novos Cartão de Cidadão .

Qual a solução para resolver o problema? Existe um fix para o erro?

**Comment by ACamposPT** [comment]
Boa tarde,
A que se refere quando refere "Isso só está a acontecer com os novos Cartão de Cidadão ."? Quais versões é que funcionam? 

Entretanto conseguimos reproduzir o problema, esse erro deve estar relacionado com a configuração de arquitectura no Visual Studio, estando a ser carregado pelo menos um DLL nativo da arquitectura errada.

**Comment by stivencamara** [comment]
Boa tarde,

Conforme o cliente explicou-me:

"...diria que há uma diferença de versão, de 003 para 006 e de 0010 para 0017… isto sem entrar em conta com o facto e que toda a cadeia de validação mudou e que há várias pessoas a reportar problemas na Internet… é só ver as imagens que anexo..."

Eu não consigo depurar a aplicação, pois não tenho acesso aos novos cartões. Veja as imagens.

**Anterior**
![Cartão anterior](https://user-images.githubusercontent.com/2065460/92412828-4fad0d00-f145-11ea-8689-a071260a7e26.JPG)

**Novo**
![Cartão novo](https://user-images.githubusercontent.com/2065460/92412837-576cb180-f145-11ea-8aee-d2a048e46178.JPG)

Sobre a aplicação, está a correr bem, exceto pelo novo Cartão de Cidadão que ocorre o erro que enviei anteriormente.

**Comment by stivencamara** [comment]
Boa tarde, peço desculpas, mas depois de análise mais cuidadosa, o cliente estava com uma versão errada da aplicação.

De qualquer forma, agradeço pela atenção.
