### ISSUE TITLE
Caracteres estranhos

### ISSUE THREAD

**Issue by tuxPT** [amagovpt/autenticacao.gov#44]
Estou a usar ArchLinux com wayland mas antes quando usava X11 não dava caracteres estranhos. Alguém com o mesmo problema ?
P.S: Os fields do cartão têm os caracteres certos

![image](https://user-images.githubusercontent.com/17715960/97885170-ee598280-1d1e-11eb-8830-7059e33c499b.png)
LOG:
[log.txt](https://github.com/amagovpt/autenticacao.gov/files/5476042/log.txt)

**Comment by ACamposPT** [comment]
Olá @tuxPT. Já conseguiste resolver o problema?

**Comment by tuxPT** [comment]
@ACamposPT era das fontes, que não estava a considerar.

**Comment by ACamposPT** [comment]
@tuxPT desculpa estar a insistir, mas podes detalhar a solução para o problema. A tua solução pode ser util para outros utilizadores, bem como, para melhorar o projecto.

Atualmente nos instaladores que fornecemos oficialmente para Linux, a fonte `Lato-Regular.ttf` é instalada pelo instalador na mesma pasta onde é colocado o binário `/usr/local/bin`. Quando a aplicação arranca esse ficheiro fonte é carregado. Qual foi a alteração que fizeste para resolver o teu problema?

**Comment by tuxPT** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=autenticacao-gov-pt-bin&id=78876563027abf0c0ea87399b5875c9c8dd1816a

**Comment by hab12335** [comment]
Estava a procurar a fonte no sitio errado, mas só resolve metade...


`
~ ❯❯❯ uname -a
Linux manjaro 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux

`
Passei duma imagem para a outra fazendo:
`
sudo cp /usr/share/fonts/TTF/Lato-Regular.ttf /usr/local/bin/Lato-Regular.ttf
`
![2020-11-14-180654_1920x1080_scrot](https://user-images.githubusercontent.com/31087004/99154027-8ef75d00-26a4-11eb-85a9-1737d2363a49.png)
![2020-11-14-180548_1920x1080_scrot](https://user-images.githubusercontent.com/31087004/99154028-90288a00-26a4-11eb-9e5f-7e074de32c83.png)

**Comment by mamoit** [comment]
Estou a ter este mesmo problema no KDE Neon (versão mais recente, clean install).
No entanto no Kubuntu 18.04 funciona bem.

**Comment by ACamposPT** [comment]
As distribuições que estão a usar não são oficialmente suportadas. No entanto, podemos dar algum suporte e tentar resolver o problema. Podem colar aqui o output da consola? Têm alguma mensagem de erro?

**Comment by mamoit** [comment]
@ACamposPT tens toda a razão.
No entanto o KDE Neon é basicamente ubuntu 20.04 com KDE e os pacotes do desktop environment updated.
Posso testar com Ubuntu 20.04 e Kubuntu 20.04 numa VM se ajudar.

**Comment by mvrk69** [comment]
Tenho o mesmo problema no Fedora 33

**Comment by mvrk69** [comment]
No Fedora 33 resolvi o problema removendo o pacote lato-fonts

**Comment by mamoit** [comment]
No KDE Neon (e ubuntu 20.04) o pacote chama-se `fonts-lato`, e é recomendado pelo `ruby2.7`.
Depois de o desinstalar (é só uma recomendação, não um requirement), o problema fica resolvido! :tada:
Obrigado @mvrk69

**Comment by mamoit** [comment]
Agora fica a dúvida...
Como é que uma fonte estar instalada parte um programa que não a usa?

**Comment by mamoit** [comment]
@ACamposPT 
> Atualmente nos instaladores que fornecemos oficialmente para Linux, a fonte Lato-Regular.ttf é instalada pelo instalador na mesma pasta onde é colocado o binário /usr/local/bin.

Por uma font no `/usr/local/bin` está longe de ser uma boa política (ter um comando chamado `Lato-Regular.ttf` na `PATH` é... pouco ortodoxo?).
É para isso que existe o `/usr/share/fonts`.
Mas IMHO a solução ideal era não instalar o ficheiro de todo e depender do pacote de sistema.

**Comment by tuxPT** [comment]
a solucao ideal é /usr/local/share. o /use/local é o que se deve usar para programas/libs/outros que não são do sistena

**Comment by tuxPT** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=autenticacao-gov-pt-bin

**Comment by tuxPT** [comment]
Este aqui usa o pacote oficial deb e adapta para achlinux

**Comment by ACamposPT** [comment]
Este problema acontece devido a uma incompatibilidade com a fonte **lato-fonts** de sistema com a fonte instalada pela nossa aplicação. Vamos resolver isso na próxima release.

No imediato, resolve o problema desinstalar o pacote de sistema "lato-fonts". 

-  Em Fedora com o seguinte comando:
`
dnf remove lato-fonts`

- Em Ubuntu, ou similares com o seguinte comando:
`
sudo apt remove fonts-lato`

**Comment by agrr** [comment]
Esta questão está resolvida da seguinte forma: em Linux a aplicação carrega a fonte lato que esteja instalada no sistema. 
Só os pacotes Windows e MacOS da versão 3.6 incluem ainda a fonte.

Assume-se que está disponível nos pacotes da distribuição o que acontece pelo menos em Ubuntu, Debian, Fedora, OpenSUSE e ArchLinux.
