### ISSUE TITLE
Tamanho do repositório

### ISSUE THREAD

**Issue by mamoit** [amagovpt/autenticacao.gov#48]
Clonei agora pela primeira vez o repositório, e espantei-me com um full clone com cerca de 700MB.

Não sei se é da doc por ter PDFs uploaded, mas se calhar não era má ideia re-pensar a documentação (não fazer commit de blobs como PDFs e ODTs) com qualquer coisa mais git friendly estilo doxygen ou mesmo markdown (que pode depois ser processado para produzir os PDFs).

Sugiro [BFG](https://rtyley.github.io/bfg-repo-cleaner/) e, se não quiserem separar os PDF e ODTs do código, podem pensar em usar [git lfs](https://git-lfs.github.com/).

**Comment by ACamposPT** [comment]
Olá @mamoit . É bem visto o teu ponto. Na verdade, nós já temos a documentação em markdown e doxygen. Posteriormente são convertidos em html (via github docs) e em PDF. Os ficheiros PDF serem guardados e estarem disponíveis para várias versões é um requisito do projecto. O que acontece é que estamos a guardar os ficheiros PDF gerados no mesmo repo.

Estamos agora a ponderar criar um repo só para a documentação, para evitar que o tamanho deste repositório cresça muito.

**Comment by mamoit** [comment]
Podem guardar os PDFs como artefactos num `doc.zip ` ou individualmente junto a cada release [aqui](https://github.com/amagovpt/autenticacao.gov/releases).
Por ex [neste repositório](https://github.com/kubernetes/kops/releases) cada release tem todas uma quantidade de ficheiros binários compilados para cada uma das plataformas, até poderiam aproveitar e fazer o mesmo, distribuindo o binário junto do código também, no entanto devido à especificidade do projecto não sei se o podem fazer.
Tens mais informação [aqui](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-releases) em como o fazer, se precisares de ajuda ou opiniões avisa.

**Comment by ACamposPT** [comment]
Devido aos riquesitos do projecto, avançamos com a seguinte solução, já implementada. Separamos a documentação do projecto e colocamos em outro repositório:

https://github.com/amagovpt/docs.autenticacao.gov

Neste novo repositório vamos disponibilizar os manuais (de todas as versões) via github pages, bem como em PDF, ambos gerados a partir de markdown. 

A documentação do SDK Java (javadocs ) e SDK C++ (doxygen), vamos também disponibilizar neste novo repositório.

Cada tag corresponde a uma versão da aplicação, sendo possivel consultar facilmente a documentação de versões anteriores.

Os  binários compilados e assinados continuam a ser disponibilizados pelo portal autenticação.gov:
https://www.autenticacao.gov.pt/web/guest/cc-aplicacao

**Comment by mamoit** [comment]
Just for the record, este problema não está resolvido:
```
$ git clone  https://github.com/amagovpt/autenticacao.gov.git
Cloning into 'autenticacao.gov'...
remote: Enumerating objects: 1416, done.
remote: Counting objects: 100% (1416/1416), done.
remote: Compressing objects: 100% (521/521), done.
remote: Total 54854 (delta 824), reused 1271 (delta 756), pack-reused 53438
Receiving objects: 100% (54854/54854), 713.56 MiB | 11.13 MiB/s, done.
Resolving deltas: 100% (34667/34667), done.
```

**Comment by ACamposPT** [comment]
Devido as características do projecto não está previsto alterar o histórico do repositório. O que garantimos com esta alteração é que o tamanho do repositório não cresce muito mais.

É sempre possível fazer clone sem fazer download de todo o histórico, com o seguinte comando:
`
git clone  https://github.com/amagovpt/autenticacao.gov.git --depth 1`
