### ISSUE TITLE
Debian 10

### ISSUE THREAD

**Issue by jmiguelf** [amagovpt/autenticacao.gov#50]
Compila e instala sem problemas... mas depois não corre:
`C++: Using application scaling.
C++: Application scaling:  1
C++: AppController started. App version:  "3.3.1 - 4000 [ 3095b81e ]"
C++: currentCpuArchitecture(): "x86_64"
C++: prettyProductName(): "Debian GNU/Linux 10 (buster)"
C++: Starting App with hardware graphics acceleration
C++: GAPI LoadTranslationFile "eidmw_nl" "/usr/local/bin/"
C++: AppController LoadTranslationFile "eidmw_nl" "/usr/local/bin/"
QQmlApplicationEngine failed to load component
qrc:/main.qml:967 Type MainForm unavailable
qrc:/MainForm.ui.qml:252 Type PageLoader unavailable
qrc:/PageLoader.qml:176 Syntax error`

**Comment by miguelblcfigueira** [comment]
Bom dia,

A função definida em PageLoader.qml:176 usa "default parameters" que só são suportados a partir da versão 5.12 do Qt. 
O Qt 5.11 instalado no Debian 10 buster ainda não suporta essa sintaxe.

**Comment by ACamposPT** [comment]
Viva,
O @miguelblcfigueira tem razão fazer update do QT para a versão 5.12 vai resolver o problema. No entanto, se não for possível podes sempre reverter o commit em que a função passou a usar "default parameters", alterando a função activateGeneralPopup para o seguinte:

```
    function activateGeneralPopup(titlePopup, bodyPopup, returnToSubMenuWhenClosed,
            linkUrl, accessibleText){

            if (linkUrl === undefined) linkUrl = ""
            if (accessibleText === undefined) accessibleText = bodyPopup 
            
            titleText.text = titlePopup
            labelText.propertyText.text = bodyPopup
            labelText.propertyLinkUrl = linkUrl
            labelText.propertyAccessibleText = accessibleText
            mainFormID.propertyPageLoader.propertyGeneralPopUpRetSubMenu = returnToSubMenuWhenClosed;

            // reduce main window opacity
            mainFormID.opacity = Constants.OPACITY_POPUP_FOCUS
            generalPopUp.visible = true;
            rectPopUp.forceActiveFocus();
    }
```
Isto deverá funcionar, no entanto, recomendamos actualizar para a versão 5.12.

**Comment by jmiguelf** [comment]
@ACamposPT solução funcional... e pelo menos por agora não me vou dar ao trabalho de compilar o QT5.12...
