### ISSUE TITLE
Quebra de linha no Nome do Cidadão na assinatura

### ISSUE THREAD

**Issue by stivencamara** [amagovpt/autenticacao.gov#53]
Boas,

Ao fazer uma assinatura em um PDF através do método **PTEID_EIDCard.SignPDF**, quando o nome do cidadão é grande, ocorre um quebra de linha e a data da assinatura fica oculta (na verdade é empurrada para baixo). Veja as imagens.

![image](https://user-images.githubusercontent.com/2065460/103693716-a579b080-4f91-11eb-9442-f8d4782a6bfb.png)
![image](https://user-images.githubusercontent.com/2065460/103693773-b88c8080-4f91-11eb-846e-ed102296720c.png)

A questão que nesse caso é habilitado o formato **small** da assinatura. Não posso utilizar do outro formato devido ao seu tamanho.

		pTEID_PDFSignature.enableSmallSignatureFormat();
		pTEID_PDFSignature.enableTimestamp();

É possível eu especificar o largura da imagem para que isso não ocorra? 
Existe alguma forma de corrigir o problema? Ou existe outra solução?

Melhores cumprimentos,
Stiven

**Comment by ACamposPT** [comment]
Boa tarde,

Não existe nenhuma configuração para o tamanho do selo da assinatura, além da opção assinatura reduzida e da assinatura visível. A assinatura reduzida está desenhada para ter 3 linhas e o tamanho da fonte é fixo.

De qualquer das formas, não existe nenhuma obrigatoriedade de colocar a data no selo da assinatura. Depois ao abrir o PDF, por exemplo no Adobe Reader, consegue ver nos detalhes da assinatura a hora da assinatura, neste caso, a hora certificada visto estar a usar timestamp.

**Comment by stivencamara** [comment]
Boas,

Eu entendo a vossa questão, mas o cliente não quer justamente ter que abrir o Adobe Reader para ver a data.

Obrigado pela resposta.

**Comment by ACamposPT** [comment]
Viva,
Mas abre o PDF em que aplicação então?

**Comment by stivencamara** [comment]
Boas,

Eu desenvolvi um projeto que utilizada a **pteidlib_dotnet.dll**. Porém o cliente fez testes também na vossa aplicação Windows e o mesmo problema ocorre.

**Comment by ACamposPT** [comment]
Sim, a nossa aplicação tem o mesmo comportamento.

**Comment by stivencamara** [comment]
Boas,

Qual é o limite máximo de caracteres para que não ocorra a quebra de linha?

**Comment by ACamposPT** [comment]
Bom dia,
Não existe um limite, é calculado dinamicamente tendo em conta a "largura" dos caracteres em causa.

**Comment by stivencamara** [comment]
Boas,

Obrigado
