### ISSUE TITLE
Validação do Selo Temporal

### ISSUE THREAD

**Issue by stivencamara** [amagovpt/autenticacao.gov#56]
Boas,

Ao configurar um servidor de Selo Temporal é possível validar o mesmo sem ter que chamar o método **SignPDF**?

```CSharp
                PTEID_PDFSignature pTEID_PDFSignature = new PTEID_PDFSignature(sourcePath);
		pTEID_PDFSignature.enableSmallSignatureFormat();
		pTEID_PDFSignature.enableTimestamp();

		card.SignPDF(pTEID_PDFSignature, page, x, y, location, reason, targetPath);
```

Algo do tipo:

```CSharp

                PTEID_Config config = new PTEID_Config(PTEID_Param.PTEID_PARAM_XSIGN_TSAURL);
		config.setString("http://timestamp.digicert.com");
                //Possível método para validar o Timestamp
                card.ValidateTimestamp();

                PTEID_PDFSignature pTEID_PDFSignature = new PTEID_PDFSignature(sourcePath);
		pTEID_PDFSignature.enableSmallSignatureFormat();
		pTEID_PDFSignature.enableTimestamp();               

		card.SignPDF(pTEID_PDFSignature, page, x, y, location, reason, targetPath);
```

O problema é que de acordo com a limitação da AMA (limite ultrapassado do Servidor do Selo Temporal - 20 em 20m), mesmo que altere a URL do servidor do Selo Temporal, temos que informar o PIN novamente pois a validação do Selo Temporal está no **SignPDF**, até onde tenho conhecimento.

**Comment by ACamposPT** [comment]
Olá,

Não é possivel verificar se já foi atingido o limite. O Selo temporal só é aplicado após a assinatura.
