### ISSUE TITLE
Obtenção da assinatura pessoal

### ISSUE THREAD

**Issue by BernardoPoiares** [amagovpt/autenticacao.gov#61]
Bom dia,

É possivel obter a assinatura mesmo da pessoa através do SDK?

**Comment by ACamposPT** [comment]
Boa tarde,

Não é possível. A assinatura manuscrita do Cidadão não esta guardada no Cartão. Qual seria o objectivo?

**Comment by BernardoPoiares** [comment]
Boa tarde,

Seria com o intuito de poder comparar com outra assinatura.
