### ISSUE TITLE
Problema Cartões Expirados - Ubuntu

### ISSUE THREAD

**Issue by devmiegsi** [amagovpt/autenticacao.gov#63]
Estou com um problema em Ubuntu a ler cartões que se encontrem expirados.

A versão foi compilada no dia 9 de março pelo que penso que seja a mais recente (segundo version.json está na 3.3.1) reparei que no mac os e no windows vai na 3.4.

Card inserted
Erro INOUT: pt.gov.cartaodecidadao.PTEID_ExSOD
Erro INOUT: -506455032
Erro INOUT: Unmapped error: -506455032

O SDK não lê o cartão, mas a aplicacao eidguiV2 no mesmo ambiente e compilado na mesma máquina lê sem problemas.

**Comment by agrr** [comment]
Boa tarde,
foi entretanto detectado e corrigido um bug na "tolerância" a cartões expirados que gerava estes erros dependendo da sequência de métodos do SDK que são invocados.
Deve atualizar o repositório e compilar de novo o SDK. 

Está em falta de facto a atualização das builds oficiais Linux, deverá ser lançada até ao final do mês a versão 3.5.0 para todos os sistemas.

**Comment by devmiegsi** [comment]
> Boa tarde,
> foi entretanto detectado e corrigido um bug na "tolerância" a cartões expirados que gerava estes erros dependendo da sequência de métodos do SDK que são invocados. Foi também prolongada esta tolerância até 31 de Dezembro.
> Deve atualizar o repositório e compilar de novo o SDK.
> 
> Está em falta de facto a atualização das builds oficiais Linux, deverá ser lançada até ao final do mês a versão 3.5.0 para todos os sistemas que incorpora estas e outras melhorias.

Se a atualização de há 3 dias tem as atualizações para linux o problema mantém-se. Primeiro fiz build por cima da anterior e nãp funcionou. Como fiquei com duvidas de quem seria o problema montei uma nova VM e instalei tudo de raiz e o problema como disse continua a acontecer.

**Comment by ACamposPT** [comment]
Se o problema ainda existe pode reabrir o ticket.
