### ISSUE TITLE
Problema com o uso de certificados da Camerfirma

### ISSUE THREAD

**Issue by somini** [amagovpt/autenticacao.gov#65]
Peço desculpa se isto não é o melhor sítio para reportar isto, podem fechar se não for.

---

O CA de muita da infrastrutura é a Camerfirma, que andou a emitir certificados com problemas, por isso vai ser removida da Root Store no dia 6 de Abril (na realidade já foi). A Google diz que vai dar mais uns dias para os sites migrarem.

https://go.theregister.com/feed/www.theregister.com/2021/02/02/chrome_camerfirma_certificates/

No Arch Linux como já tem os updates mais recentes isto já acontece há algumas semanas. Havia outros sites como o https://sapo.pt, que já migram.

Tentei adicionar umas excepções mas como são muitos domínios, não é fácil conseguir que o site funcione.

---

PS: O Let's Encrypt suporta wildcards agora, FYI. Só Domain Validated ainda.

**Comment by ACamposPT** [comment]
Olá,

Este tema já está a ser tratado pela AMA, deverá ficar resolvido em breve.  Para mais detalhes sobre este tema envie um e-mail para info.cidadao@ama.pt.

No entanto, em principio a aplicação local Autenticação.gov não é afectada por este tema. Detectou alguma dificuldade na aplicação?

**Comment by somini** [comment]
> No entanto, em principio a aplicação local Autenticação.gov não é afectada por este tema. Detectou alguma dificuldade na aplicação?

Não, só detectei problemas no site.

> Este tema já está a ser tratado pela AMA, deverá ficar resolvido em breve.

Obrigado, posso fechar esta issue nesse caso.
