### ISSUE TITLE
Problems with download agent at aplicacoes.autenticacao.gov.pt

### ISSUE THREAD

**Issue by a36233** [amagovpt/autenticacao.gov#68]
If you download plugin-autenticacao-gov.deb from wget, you get a different version than if you download it from a browser.

$ rm -rf plugin-autenticacao-gov.deb && wget https://aplicacoes.autenticacao.gov.pt/plugin/plugin-autenticacao-gov.deb && sha512sum plugin-autenticacao-gov.deb
--2021-04-15 14:39:59--  https://aplicacoes.autenticacao.gov.pt/plugin/plugin-autenticacao-gov.deb
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving aplicacoes.autenticacao.gov.pt (aplicacoes.autenticacao.gov.pt)... 13.107.213.19, 13.107.246.19, 2620:1ec:bdf::19, ...
Connecting to aplicacoes.autenticacao.gov.pt (aplicacoes.autenticacao.gov.pt)|13.107.213.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1076254 (1.0M) [application/octet-stream]
Saving to: ‘plugin-autenticacao-gov.deb’

plugin-autenticacao-gov.deb            100%[=========================================================================>]   1.03M  --.-KB/s    in 0.05s   

2021-04-15 14:39:59 (19.5 MB/s) - ‘plugin-autenticacao-gov.deb’ saved [1076254/1076254]

6f2b8a52b41755fd2929e8d955c37426e52ed8066b745b5d34d3270692e6dc10c649ca5994602201d618bfd07421de10c447347e44502228ecc574df4a004dbe  plugin-autenticacao-gov.deb

Browser download: https://aplicacoes.autenticacao.gov.pt/plugin/plugin-autenticacao-gov.deb
$ sha512sum plugin-autenticacao-gov.deb 
ab33e15c7440d97d71869ff96896258038ea1167e6fb31dda3a34f1f5208befd3965d2a0983362c4a3f84c34fd181c1e8016889fc6fe040450a67cc4b5b953e0  plugin-autenticacao-gov.deb

**Comment by agrr** [comment]
Esta questão está relacionada com o issue que foi reportado hoje #71 

O hash SHA-512 da versão 2.0.60 do plugin-autenticacao-gov.deb, versão atual ao dia de hoje é o seguinte:
`ab33e15c7440d97d71869ff96896258038ea1167e6fb31dda3a34f1f5208befd3965d2a0983362c4a3f84c34fd181c1e8016889fc6fe040450a67cc4b5b953e0`

Fomos entretanto informados pela AMA que existia um problema na atualização desta release na CDN que está a distribuir os mesmos o que originava que nalguns casos fosse descarregada a versão anterior do plugin.

Já deverá estar resolvido, obrigado pelo feedback
