### ISSUE TITLE
lato-fonts-2.015-10.fc33.noarch.rpm incompativel com sergiomb/pteid-mw

### ISSUE THREAD

**Issue by cgms33** [amagovpt/autenticacao.gov#69]
Autentificaçao.gov ilisivel com erros de fonte apos instalaçao com fedora copr sergiomb/pteid-mv . Necessita remover lato-fonts package para resolver problema (permanece erros : "  cheiro" em vez de "ficheiro", "certi  cado" em vez de "certificado"). Operating System: Fedora 33 (Workstation Edition), Kernel: Linux 5.11.14-200, Architecture: x86-64
![2021-04-18 16-38-17](https://user-images.githubusercontent.com/82766517/115150309-112ae980-a068-11eb-9cb8-2997495ba07d.png)
![2021-04-18 16-55-02](https://user-images.githubusercontent.com/82766517/115150385-5f3fed00-a068-11eb-9e8b-117fc76edddd.png)

**Comment by ACamposPT** [comment]
Já experimentou instalar a versão oficial:

https://www.autenticacao.gov.pt/web/guest/cc-aplicacao

**Comment by cgms33** [comment]
nao consigo :  "qt5 is required for pteid-mw-3.5.0.git20210329-1.1.x86_64" apesar de ter instalado antecipadamente adwaita-qt5, libadwaita-qt5, polkit-qt5-1, poppler-qt5, qca-qt5, qca-qt5-ossl, qt5-qtbase, qt5-qtbase-common.noarch, qt5-qtbase-gui, qt5-qtcharts, qt5-qtdeclarative, qt5-qtgraphicaleffects, qt5-qtquickcontrols, qt5-qtquickcontrols2, qt5-qtsvg, qt5-qtwayland, qt5-qtx11extras, qt5-qtxmlpatterns, qt5-rpm-macros.noarch, qt5-srpm-macros.noarch, quazip-qt5

**Comment by agrr** [comment]
Boa tarde,
houve um erro na publicação da versão 3.5.0 para Fedora e como tal o pacote que estava disponível até ao dia de ontem não tinha essa correção nas dependências do RPM.

Já é possível instalar no Fedora 32 e 33.
