### ISSUE TITLE
assinatura de documentos - permitir assinatura vísivel em apenas uma página

### ISSUE THREAD

**Issue by gvlx** [amagovpt/autenticacao.gov#70]
versão 3.5.0 - 4271, revisão 3b9a9429, linux Fedora 33.

A presente versão da app não permite colocar a assinatura digital numa só página que não seja a última.

A versão web permite.

As opções actuais são: em todas as páginas; na última página; não visível (em nenhuma página).

Do que me pareceu do código, este permite designar _a_ página onde colocar a assinatura, não está limitado à última página.

Será apenas uma questão de flexibilizar o UI?

**Comment by ACamposPT** [comment]
Boa tarde,

Pensamos que esteja a fazer alguma confusão.

As opções para colocar o selo de assinatura são: escolher uma página ou a última página. Não existe a opção "em todas as páginas", nem é possível assinar em múltiplas páginas. 

Uma assinatura digital cobre sempre todo o documento.

**Comment by gvlx** [comment]
Não falo da assinatura digital, tal que forma de autenticação de um documento inteiro.

Falo da aposição de um indicador visual.

E sim, estava enganado, a aposição é na página indicada e visualizada e não em todas.

Estava a ser levado em erro ao considerar a que pequena visualização representava o documento inteiro e não apenas a página escolhida.

As minhas desculpas.
