### ISSUE TITLE
Pacotes para compilação em Ubuntu 21.04?

### ISSUE THREAD

**Issue by pkoch** [amagovpt/autenticacao.gov#72]
Tentanto correr as vossas instruções para instalar os pacotes de compilação, o `apt` dá-me o seguinte erro:
```
$ sudo apt install build-essential libpcsclite-dev libpoppler-qt5-dev libzip-dev libopenjp2-7-dev libpng-dev openjdk-11-jdk qtbase5-dev qt5-qmake qtbase5-private-dev qt5-default qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick-controls2 libssl-dev libxerces-c-dev libxml-security-c-dev swig libcurl4-nss-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package qt5-default
```

Eu não tenho experiencia em qt para saber como proceder. Qual o pacote que devo usar em vez do `qt5-default`?

**Comment by Raidenkyu** [comment]
Acho que o problema é mesmo do lado do Ubuntu, que se esqueceu de incluir o pacote na última versão do Ubuntu, visto que até à versão 20.10 ainda existe o pacote. Já com o `libzip5` foi igual. Deve ser uma questão de tempo até resolverem, mas de qualquer das formas talvez esta solução possa ajudar:

https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04

**Comment by agrr** [comment]
Boa tarde @pkoch,

no Ubuntu 21.04 pode ser removido da lista de dependências o pacote `qt5-default`.
De qualquer forma nas próximas semanas será lançada a versão 3.6.0 com um pacote para Ubuntu 21.04.

**Comment by agrr** [comment]
Já está disponível a build oficial para Ubuntu 21.04 e para quem pretender recompilar em distros Debian-based pode usar as dependências atualizadas indicadas no ficheiro `debian/control` do projeto:

https://github.com/amagovpt/autenticacao.gov/tree/master/pteid-mw-pt/_src/eidmw/debian/control
