### ISSUE TITLE
Versão miníma JDK 11

### ISSUE THREAD

**Issue by amsimoes** [amagovpt/autenticacao.gov#73]
Viva,

Apesar de no manual do SDK ditar que os requisitos de compiladores são:

"Java - Oracle JDK 8 ou superior"

Ao tentar compilar com essa mesma versão (java 8 - 52.0), sucede este erro:

```
(...) pteidlibj.jar!/pt/gov/cartaodecidadao/PTEID_ReaderSet.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath."
```

O novo requisito é Java 11?
Alguma maneira de resolver, para usar com Java 8?

**Comment by agrr** [comment]
Boa tarde,

na versão 3.5.0 do software o SDK Java incluído nas builds Linux e Windows não estava de facto compatível com Java 8.

Esta situação foi corrigida na release 3.6.0, tendo em conta que o Java 8 ainda é suportado.

Obrigado pelo report
