### ISSUE TITLE
Bloqueio do Cartão de Cidadão por tentativa de assinatura digital

### ISSUE THREAD

**Issue by MariaTeresaFerreira** [amagovpt/autenticacao.gov#75]
Usando o código fornecido na [documentação](https://amagovpt.github.io/docs.autenticacao.gov/manual_sdk.html#assinatura-digital) para assinatura digital com o Cartão de Cidadão, os cartões que usei ficaram imediatamente bloqueados. 
Não devo estar a chamar nada de forma errada porque chega a aparecer-me a janela de pop-up para inserir o código de assinatura.

Há alguma maneira de contornar isto ou alguma alternativa (pe. algum modo de teste que nao implique usar cartões reais para testar o código)? 

Obrigada desde já por qualquer ajuda

**Comment by agrr** [comment]
Bom dia,

A nossa suspeita é que os cartões que testou não deveriam ter a assinatura ativa o que significa que o PIN de assinatura estava bloqueado à partida. O comportamento de aparecer a janela de PIN faz sentido para este cenário porque os métodos de assinatura não validam previamente se os PINs estão de facto desbloqueados.

Essa validação pode ser feita programaticamente com o seguinte código (em Java):

```java

   //eidCard é um objecto do tipo PTEID_EIDCard

   PTEID_Pins pins = eidCard.getPins();
   PTEID_Pin signature_pin = pins.getPinByPinRef(PTEID_Pin.SIGN_PIN);

   if (signature_pin.getTriesLeft() == 0) {
        System.out.println("PIN de assinatura bloqueado.");
   }

```

**Comment by MariaTeresaFerreira** [comment]
Boa tarde,
Eu antes de testar com o meu código, usei a aplicação disponível para testar que estava tudo ok, portanto o PIN estava desbloqueado inicialmente.

**Comment by ACamposPT** [comment]
Boa tarde,

Pode desbloquear o Cartão numa loja do Cidadão sem custos. Contudo, dependendo da versão do Cartão pode ser necessário a Carta com os PIN's. Se colocar aqui um excerto do código, podemos tentar identificar o problema.

Entretanto colocamos exemplos completos de usa do SDK, aqui:

https://github.com/amagovpt/docs.autenticacao.gov/tree/main/SDK_Examples

Existe Cartões de Teste para as equipas de desenvolvimento, e também para entidades externas. Sobre os cartões de teste, deverá contactar a AMA e indicar qual o objectivo para o qual pretende os Cartões de Teste. Contactar pelo email:

info.cidadao@ama.pt.

**Comment by tiagozaccaro** [comment]
Porque nao existe uma forma de desbloquear o pin usando a carta, mas sem ter que ir no balcao, porque mesmo indo no balcao as vezes o pin nao e alterado, existe essa posibilidade ou o software de desbloqueio so esta disponivel para os balcoes?
