### ISSUE TITLE
Validação e Assinatura de documentos com assinatura no formato ASiC-E

### ISSUE THREAD

**Issue by jorgedsmatias** [amagovpt/autenticacao.gov#77]
Bom dia,

Descobri que há um novo formato de ficheiro para associar assinatura digitais a qualquer tipo de documento que não suporte assinaturas embebidas. 
O formato chama-se ASiC-E e parece fazer parte de uma família designada DigiDoc. Este parece estar aprovado pela Comissão Europeia [1] para troca de documentos de qualquer tipo formato, em que o processo de assinatura constrói um ficheiro ZIP, mas com extensão ".asice", e lá dentro está contido  o ficheiro do documento original, um ficheiro XML que contêm as assinaturas e mais alguns ficheiros com metainformação sobre a estrutura dentro ZIP.

Pelo que constatei, nem a aplicação do Cartão de Cidadão, nem a página Web online para assinatura com Chave Móvel Digital suportam a realização de assinaturas cumulativas em cima de documentos com assinatura no formato ASiC-E.

Encontrei no site da União Europeia uma aplicação demo que assina e valida assinaturas em formato ASiC-E [3][4].

Alguns países, como a Estónia, já usam este formato [5] e fornecem software para assinar os seus documentos neste formato [6].

Pergunto se o software "Autenicacao.Gov" eventualmente terá a utilização deste formato no seu Roadmap?

Referências:
[1] https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eSignature+standards
[2] https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/DSS+releases
[3] https://ec.europa.eu/cefdigital/DSS/webapp-demo/sign-a-document
[4] https://ec.europa.eu/cefdigital/DSS/webapp-demo/validation
[5] https://www.ria.ee/en/state-information-system/trust-services/eidas.html
[6] https://www.id.ee/en/article/install-id-software/

**Comment by ACamposPT** [comment]
Boa tarde,

A aplicação Autenticação.gov para computador, já tem implementada a funcionalidade de assinaturas XAdES, no entanto, apenas para assinaturas com o Cartão de Cidadão. Nas opções avançadas, selecione "Outros Ficheiros".

No manual de utilização verifique o tópico "Tipo de assinatura" em:

https://amagovpt.github.io/docs.autenticacao.gov/user_manual.html#assinatura-digital

Assinaturas XAdES com Chave Móvel Digital está na nossa lista de novas funcionalidades a implementar, mas não temos previsão para quando vai estar disponível.

**Comment by agrr** [comment]
Em relação ao comentário do @ACamposPT acrescento que o tipo de assinatura que implementamos na opção "Outros ficheiros" é o XAdES em modo _detached_ distribuído em container ASiC-E. 

As principais limitações que ainda temos em relação à assinatura PDF (PAdES): 
* Não é possível assinar com Chave Móvel Digital
* Múltiplas assinaturas sobre o mesmo conjunto de ficheiros

**Comment by agrr** [comment]
Na versão 3.8.0 já estão implementadas a assinatura de "Outros ficheiros" com Chave Móvel Digital em container ASIC que pode ser posteriormente re-assinado por mais assinantes.

Para a versão 3.9.0 vamos adicionar a possibilidade de extrair e abrir ficheiros de um container no momento da assinatura.
