### ISSUE TITLE
Problemas a assinar documentos com a versão 3.6

### ISSUE THREAD

**Issue by mobilwave** [amagovpt/autenticacao.gov#79]
Bom dia,

Em alguns computadores, depois de actualizarmos a aplicação para a versão 3.6, deixaram de conseguir assinar documentos.
O cartão é reconhecido pelo software autenticação.gov, a assinatura através do vosso software funciona bem, mas se tentarmos usar por exemplo o acrobat Reader ou outra aplicação, o certificado não está disponível.

Se no computador fizermos o downgrade para a versão 3.4 ou 3.5, a assinatura começa a funcionar novamente bem no acrobat reader e em outras aplicações.

Não conseguimos encontrar um padrão porque é que não funciona só em alguns computadores.
No entanto esta situação é bastante importante para nós, porque é complicado estarmos a fazer downgrade e pedir aos utilizadores para não actualizarem a versão.

Estamos ao dispor para qualquer informação que necessitem.

**Comment by agrr** [comment]
Boa tarde,

esses sintomas apontam para um problema na instalação/upgrade do componente minidriver do Autenticação.gov que é utilizado as aplicações Windows como o Adobe Reader. 
Houve de facto uma alteração na instalação deste componente na versão 3.6.0 mas ainda não tinha sido detetado ou reportado qualquer problema.

Para ajudar ao nosso diagnóstico pedimos que façam uma reinstalação da versão 3.6.0 num dos computadores afetados com log de diagnóstico através deste comando executado como administrador:

```
msiexec /i [MSI_PATH]\Autenticacao.gov_Win_x64_signed.msi /L*V "pteid-install.log"
```

Pedimos em seguida que partilhem o log gerado no ficheiro `pteid-install.log` e que verifiquem se os erros se mantêm nas assinaturas em Adobe Reader ou outras aplicações que usem o certificado registado no Windows.

Como quickfix para evitarem o downgrade do software podem noutras máquinas também afetadas reinstalar o minidriver seguindo este método:
https://amagovpt.github.io/docs.autenticacao.gov/user_manual.html#impossibilidade-de-assinatura-em-adobe-reader-microsoft-office-e-libreoffice-com-cart%C3%A3o-de-cidad%C3%A3o

Obrigado

**Comment by mobilwave** [comment]
Muito obrigado pela resposta André.

Voltei a instalar a versão 3.6 e envio o log em anexo e continuou a não funcionar a assinatura pelo Acrobat Reader.

Fizemos a instalação manual do minidriver como indicaste passou a funcionar.

Se for preciso o log de mais alguma máquina, avisa.

[pteid-install.log](https://github.com/amagovpt/autenticacao.gov/files/6746898/pteid-install.log)

**Comment by agrr** [comment]
Podem indicar por favor pelo menos um número de versão do/s CC utilizado no teste de ontem ?
Esses números encontram-se no verso do cartão tal como indicado aqui na página 3:

https://www.autenticacao.gov.pt/documents/20126/115760/Controlo+de+Vers%C3%B5es+do+Documento.pdf/656a83ab-4b84-080b-0f86-4bd5e188ed10

**Comment by mobilwave** [comment]
Boa tarde,

 

A versão que usamos foi a 006.007.23

 

Melhores Cumprimentos

 

David Rato

 

      <https://www.certipedia.com/quality_marks/9000000055?locale=en> 

 <http://www.mobilwave.pt/> www.mobilwave.pt |  ***@***.***> ***@***.***

Rua da Prata, 59 – 3º Esq. | 1100-413 LISBOA | Telef. +351 213 155 260

**Comment by agrr** [comment]
Já foi publicada a versão 3.6.1 para Windows que inclui a correção para esta questão.
