### ISSUE TITLE
Certificado Assinatura Digital, PrivateKey deixou de estar disponível na versão 3.6.0

### ISSUE THREAD

**Issue by JAL-Abaco** [amagovpt/autenticacao.gov#80]
Bom dia,

temos uma aplicação em C# que permite assinar documentos através dos certificados instalados pela aplicação autenticação.gov na store do utilizador.

No entanto desde esta ultima versão 3.6.0 que quando acedemos aos certificados de assinatura digital do utilizador através da **_X509Store_** para obtermos o certificado em **_X509Certificate2_** o campo **_PrivateKey_** deixou de estar preenchido, sendo que depois o processo de assinatura falha porque o par de chaves não está disponível para proceder à assinatura.

Neste momento temos pedido aos nossos clientes para não atualizarem a aplicação autenticação.gov até conseguirmos perceber e resolver a situação, no entanto está a causar imensos constrangimentos.

Se precisarem de mais informação por favor indiquem.

**Comment by agrr** [comment]
Boa tarde,

detetámos entretanto um issue no instalador da v 3.6.0 que deverá causar este comportamento para aplicações que usem as assinaturas através dos certificados do sistema (CryptoAPI) se forem aplicações em modo 32-bit a correr em Windows 64-bit.

Pedimos que adicione uma chave de registo em falta através do seguinte ficheiro .reg:

[Pteid-CSP-key.zip](https://github.com/amagovpt/autenticacao.gov/files/6750334/Pteid-CSP-key.zip)

Também deverá funcionar a instalação manual do componente _minidriver_ tal como recomendámos no issue #79 mas é preferível para nós usar esta chave de registo que se testada com sucesso será integrada no instalador da próxima release.

Pedimos desculpas pelo incómodo causado.

**Comment by PFreitas93** [comment]
Boa tarde,

A nossa aplicação de assinatura também começou a apresentar problemas com esta nova versão, 3.6.0, mas após adicionar este ficheiro reg, começou novamente a funcionar normalmente

**Comment by agrr** [comment]
Já foi publicada a versão 3.6.1 para Windows que inclui a correção para esta questão.
