### ISSUE TITLE
Crash (GSOD) após upgrade do Windows 10 para Windows 11 (Beta)

### ISSUE THREAD

**Issue by pedrolamas** [amagovpt/autenticacao.gov#82]
A Microsoft prepara-se para lançar o novo Windows 11 em breve, e neste momento já é possível experimentar o mesmo bastando para isso registar no programa Windows Insider - algo que eu faço parte faz alguns anos já!

Acontece que ao fazer upgrade do Windows 10 para o 11 via Windows Update (Windows Insider Beta Channel), um crash (Green Screen of Death) ocorre ao iniciar pela primeira vez o novo sistema operativo.

![image](https://user-images.githubusercontent.com/85504/127887909-a45ae117-3437-4e48-9123-7e3c98234618.png)

Note-se que nada nessa imagem faz identificar a origem do problema para além de parecer que se trata de um problema com um driver de rede.

No entanto, mais utilizadores começaram a queixar-se do mesmo [neste post](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/tcpipsys-error-windows-insider-program/3ab79955-9128-40f2-b7f7-d4a2a626a54a) nos fóruns da Microsoft.

A dada altura deparei-me que TODOS os utilizadores nesse post eram Portugueses(!), e rapidamente começamos a cruzar informações para tentar identificar o problema que nos afectava apenas a nós.

A minha máquina tem todas as definições regionais para UK e não tenho qualquer teclado (seja físico ou apenas o "layout") em PT, daí que isso não poderia ser!

Sugeri aos outros utilizadores para verificarem se tinham a Aplicação Autenticação.gov e o plugin instalados, o que alguns confirmaram que sim.

Em conclusão, **após desinstalada a Aplicação Autenticação.gov, o upgrade para Windows 11 funcionou sem problemas** para todos os utilizadores que assim experimentaram, tal como pode ser visto ao longo daquele post.

**Comment by dwjorgeb** [comment]
Estou a ter o mesmo problema, tive de desinstalar completamente a app para conseguir fazer o update do Windows

**Comment by ACamposPT** [comment]
Olá,

Ainda não tivemos oportunidade de fazer os testes de upgrade do Windows. Ficamos agradecidos pelo trabalho que já desenvolveram vocês.

Assim para tentarmos resolver o problemas gostaríamos de saber o seguinte:

1) Qual era a versão da aplicação autenticação.gov que tinham instalado antes de fazer o Upgrade?

2) Na versão 3.6.1 foram feitas alteração à forma como o modulo "Minidriver do Cartão do Cidadão" é instalado no computador. 
Este modulo permite que aplicações externas possam usar as funcionalidade criptográficas do Cartão de Cidadão via modulo Criptográfico do Windows. Este modulo é possível ser instalado (opção default) ou não ser instalado, usando as opções de instalação avançadas. 

Ver: https://amagovpt.github.io/docs.autenticacao.gov/user_manual.html#instala%C3%A7%C3%A3o-em-microsoft-windows

Assim, gostaríamos de pedir para testarem fazer o upgrade do Windows com a versão 3.6.1 da aplicação Autenticação.gov, com o Minidriver instalado e sem estar instalado. Existe alguma diferença de comportamento?

Pelas evidencias que apresentam, suspeitamos do Minidriver pois é um driver, mas na verdade, não temos qualquer evidencia que seja a razão do problema e não um bug do Windows, que seja de alguma forma só aparece quando a aplicação Autenticação.gov está instalada.

**Comment by pedrolamas** [comment]
> * Qual era a versão da aplicação autenticação.gov que tinham instalado antes de fazer o Upgrade?

Não consigo dizer com toda a certeza, mas tinha actualizado nas ultimas semanas, e penso que a que estava era mesmo a 3.6.1 (instalada com todos os defaults)

Concordo com a vossa indicação, tudo parece apontar para algum problema com o minidriver, isso faria todo o sentido dado a "solução" de desinstalar a app.

Neste momento não consigo fazer o teste que pedem dado ter já actualizado a máquina em causa para Windows 11... mas posso avançar que após o upgrade, já reinstalei a versão 3.6.1 da app e testei com o CC e agora está a funcionar sem qualquer problema!

**Comment by victorfs78** [comment]
Bom dia,

Acabei de fazer a actualização do meu computador do Windows 10 para o Windows 11 Beta (Windows 11 Insider Preview 10.0.22000.100) e tinha o mesme error que @pedrolamas .

Primeiro tentei actualizar com o Autenticaçao.gov 3.4.0 instalado no meu computador, mas não funcionou. Erro: ecrã verde com erro tcpip.sys.
Depois de actualizar o Autenticaçao.gov go 3.6.1, reiniciar o computador e voltar a descarregar o W11 usando o Windows Update... mesmo erro :/
E, depois de remover o Autenticaçao.gov, relancei a actualização... e funcionou desta vez.

Encontrei essas erros registado no Event Viewer com a hora quando fizei as actualizações, que menciona a app Autentificaçao, se ajudar:

![Screenshot 2021-08-03 192532](https://user-images.githubusercontent.com/18636021/128065441-98b06e82-ea18-4bfe-81b3-c374ce36c2f4.jpg)

**Comment by victorfs78** [comment]
Bom dia,

Acabei de fazer a actualização do meu computador do Windows 10 para o Windows 11 Beta (Windows 11 Insider Preview 10.0.22000.100) e tinha o mesme error que @pedrolamas .

Primeiro tentei actualizar com o Autenticaçao.gov 3.4.0 instalado no meu computador, mas não funcionou. Erro: ecrã verde com erro tcpip.sys.
Depois de actualizar o Autenticaçao.gov para a versão 3.6.1, eu reiniciei o computador e voltar a descarregar o W11 usando o Windows Update... mesmo erro :/
E, depois de remover o Autenticaçao.gov, relancei a actualização... e funcionou desta vez.

**Comment by pedro7** [comment]
FYI A instalação da aplicação após o upgrade não causa problemas.

![image](https://user-images.githubusercontent.com/220099/131827001-b83ce91d-82db-4586-9e69-a1d67cb68f65.png)

**Comment by yann-mrt** [comment]
Good day, 
I'm French leaving in Portugal with Autenticaçao.gov (3.6.1) installed (not sure if it was with mini driver or not I just installed by default) This was causing BSOD with TCPIP.SYS problem when upgrading win 10 to win 11 (10.0.22000.160). I try lot of think like updae all driver,  disk error... After uninstalling Autenticaçao.gov update is done.

**Comment by ACamposPT** [comment]
A equipa de desenvolvimento esteve a analisar o problema, e concluí que o problema existe apenas no upgrade do Windows 10 para Windows 11, quando a aplicação Autenticação.Gov está instalada.

Pelos testes que efetuamos em versões beta do Windows 11, a aplicação Autenticação.Gov funciona perfeitamente em Windows 10 e Windows 11.

**O procedimento recomendado no imediato aos utilizadores que pretendem atualizar os sistemas para Windows 11 é desinstalar a aplicação "Autenticacao.gov" antes do upgrade para Windows 11 e voltar a instalar após o upgrade.**

A equipa de desenvolvimento está em contacto com a Microsoft Portugal para resolver o problema, tudo indica que o problema se deve ao instalador do Windows 11 que gera uma corrupção em configurações (chaves de registo do Windows) essenciais para o arranque do sistema aquando do registo de um componente da aplicação Autenticação.Gov.

Mais detalhes técnicos podem ser encontrados no ticket criado nas plataformas da Microsoft:

https://answers.microsoft.com/en-us/windows/forum/windows_11/developer-question-windows-11-upgrade-failed-with/0db14787-539b-4dbc-903c-73229e689b9c

**Comment by shadypt** [comment]
No meu caso fiz uma instalação limpa do W11 e após instalar a aplicação reiniciei e tive novo BSOD. 
Acabei por instalar novamente o W10 e vou aguardar que a MS resolva o problema numa futura atualização cumulativa.

**Comment by shadypt** [comment]
https://docs.microsoft.com/en-us/windows/release-health/status-windows-11-21h2#1698msgdesc

**Comment by agrr** [comment]
No link partilhado pelo @shadypt já tem parte da explicação mas clarificando o estado atual do caso:

a Microsoft bloqueou para já a disponibilização do upgrade para Windows 11 a quem tenha instalada a aplicação de modo a evitar incómodos ao utilizador comum.

Pelo que nos informaram a correção definitiva deverá ser incluída nos updates do Windows do mês de Novembro, na *patch Tuesday* de Novembro e a partir daí passará a ser disponibilizado aos utilizadores do Autenticação.gov o upgrade para Windows 11.

**Comment by shadypt** [comment]
Penso que a MS já tenha lançado a correção para o canal beta.
https://blogs.windows.com/windows-insider/2021/10/15/releasing-windows-11-build-22000-282-to-beta-and-release-preview-channels/
Terceiro parágrafo.
Confirmam?

**Comment by agrr** [comment]
Está confirmada a resolução do bug e a Microsoft já levantou o bloqueio à atualização para Windows 11.
Obrigado a todos pela colaboração.
