### ISSUE TITLE
Mac OS erro

### ISSUE THREAD

**Issue by ElianoMarques** [amagovpt/autenticacao.gov#83]
A versao 3.6 da um erro constante quando colocamos o nr de telefone e pin. 

A versao anterior 3.5.2 funcionava perfeitamente. 

podem ajudar? Tambem ja mandei email e nao obtive resposta.

**Comment by ACamposPT** [comment]
Boa tarde,

Deve seguir este procedimento e contactar a linha de suporte:

https://amagovpt.github.io/docs.autenticacao.gov/user_manual.html#obten%C3%A7%C3%A3o-do-relat%C3%B3rio-para-an%C3%A1lise-atrav%C3%A9s-do-menu-configura%C3%A7%C3%B5es
