### ISSUE TITLE
Aplicacao nao deteta o leitor de cartoes

### ISSUE THREAD

**Issue by jorgebnunes** [amagovpt/autenticacao.gov#84]
Possuo um toshiba Tecra S11 (antigo) que tem um O2Micro Smart Card Reader e tem o Windows 10 64bit versao 21H1 v19043.1202
Neste momento a aplicaçºao nao deteta o leitor de cartoes mas garanto que em versoes anteriores do SO o leitor funcionou sem problemas. Também aparece no gestor de dispositivos como detetado.
Conseguem ajudar na resolucao deste problema?
Precisam de mais feedback?
Obrigado.

**Comment by ACamposPT** [comment]
Boa tarde,

Pode experimentar o leitor em outro computador para verificar se o problema é do leitor.

**Comment by jorgebnunes** [comment]
Boa tarde.

Liguei o Card Reader da Gemalto (versão inicial vendida no IRN) no portátil, foi detetado, mas a aplicação Autenticacao.gov não deteta o dispositivo.

Voltei a ligar este card reader no meu macOS e funcionou sem problemas.

Obrigado.

**Comment by ACamposPT** [comment]
Olá,

Poderá ser problema de drivers no computador, ou algo com serviço de smart cards. De qualquer forma,  se não conseguir resolver o problema deverá seguir as instruções do manual para "Obtenção do relatório para análise" e seguir todo o procedimento.

https://amagovpt.github.io/docs.autenticacao.gov/user_manual.html#obten%C3%A7%C3%A3o-do-relat%C3%B3rio-para-an%C3%A1lise-atrav%C3%A9s-do-menu-configura%C3%A7%C3%B5es
