### ISSUE TITLE
Incompatibilidade com Java 8 na versão 3.6.1 do SDK Java para Windows

### ISSUE THREAD

**Issue by nuckrieg** [amagovpt/autenticacao.gov#86]
Com a última versão do autenticacao.gov (3.6.1), o pteidlibj aparenta ter sido compilado com Java 11, o que causa problemas de integração da library com aplicações que estejam a funcionar com Java 8. 

Tal mudança (significativa) não se encontra presente nas version update notes.

**Comment by ACamposPT** [comment]
Boa tarde,

Efetivamente verificamos que a versão 3.6.1 do SDK para Windows foi gerada sem compatibilidade para Java 8. 
Vamos corrigir isso na próxima versão.

**Comment by ACamposPT** [comment]
Corrigido na versão 3.7.0
