### ISSUE TITLE
Firefox em Ubuntu vai passar a ser um pacote snap

### ISSUE THREAD

**Issue by allnamesaretakeningithub** [amagovpt/autenticacao.gov#87]
https://www.omgubuntu.co.uk/2021/09/ubuntu-makes-firefox-snap-default

Isto pode ter impacto com a aplicação e plugin de autenticação. Porque snaps não conseguem comunicar as bibliotecas PKCS 11 no systema anfitrião

**Comment by agrr** [comment]
Boa tarde,
confirma-se que não funciona o carregamento do módulo libpteidpkcs11 na versão Snap do Firefox.

Para já a alternativa para quem necessitar deste módulo é utilizar o pacote tradicional ainda disponível nos repositórios do Ubuntu ou o Firefox para Linux disponibilizado diretamente pelo Mozilla (em arquivo .tar.bz2)
