### ISSUE TITLE
Acrobat Reader deixou conseguir assinar depois de atualização para a versão 3.7.0 (macOS)

### ISSUE THREAD

**Issue by jmaferreira** [amagovpt/autenticacao.gov#89]
Depois de atualizar a aplicação Autenticacao.gov.pt o acrobat reader deixou de conseguir assinar PDFs.

Quando tento associar o PKCS#11, o Acrobat dá um erro:

<img width="421" alt="Screenshot 2021-12-22 at 21 34 02" src="https://user-images.githubusercontent.com/3181302/147157903-d927d072-5620-4d28-8019-75481272dd12.png">

<img width="884" alt="Screenshot 2021-12-22 at 21 34 16" src="https://user-images.githubusercontent.com/3181302/147157826-d9ccf17c-7ff7-45e2-b110-e9d75f685103.png">

**Comment by agrr** [comment]
Viva @jmaferreira, 

está a utilizar um Mac com processador M1? 
Se for esse o caso para utilizar o nosso módulo PKCS#11 terá de executar o Adobe Reader em modo emulado. 
A aplicação MacOS e as bibliotecas incluídas ainda só suportam nativamente processadores Intel.

Pode desabilitar o "native OS mode" do Adobe Reader como está indicado aqui:
https://helpx.adobe.com/acrobat/kb/apple-silicon-m1-processor-support.html

**Comment by jmaferreira** [comment]
Viva,

Obrigado. Era isso mesmo. Continuação de bom trabalho.
