### ISSUE TITLE
Inconsistência entre mensagem de erro de autenticação de site e de aplição

### ISSUE THREAD

**Issue by InesAlbano** [amagovpt/autenticacao.gov#92]
A minha chave móvel digital foi bloqueada. Quando me tento autenticar no site, recebo um SMS a dizer "Tentativa de autenticação com Chave Móvel Digital sem conta ativa.". No entanto, quando me tento autenticar na aplicação recebo SMS a dizer "A sua Chave Móvel Digital encontra-se bloqueada.".

Tal é **inconsistente** para o utilizador.

**Comment by agrr** [comment]
Obrigado pelo feedback mas a mensagem que aparece no SMS não depende deste projeto em particular mas sim do serviço da Chave Móvel Digital operado pela AMA.

Seria mais interessante reportar esta questão diretamente à AMA através do e-mail info.cidadao@ama.pt
