### ISSUE TITLE
Cert

### ISSUE THREAD

**Issue by Jonathanfelipe28** [amagovpt/autenticacao.gov#95]
https://github.com/servicosgovbr/manual-script-chatbot-login-unico/blob/7976fdc64d302795e5f1172a98cde652b47306ac/_perguntasdafaq/problemanacontadeacessocomertificadodogital.rst

**Comment by agrr** [comment]
Deverá ter aberto este ticket por engano, colocou apenas um link para um projeto brasileiro que não conhecemos 🤷🏻‍♂️
