### ISSUE TITLE
Trying to compile source code  for open suse 15.3

### ISSUE THREAD

**Issue by RuiMeirinho** [amagovpt/autenticacao.gov#98]
Boa Noite,

Estou a tentar compilar o source code para a versão   openSUSE Leap 15.3
No entanto estou a obter o seguinte erro:  Project ERROR: libopenjp2 development package not found
Verifico no yast que tenho este pacote instalado.

libopenjp2-7 - Opensource JPEG 2000 Codec Implementation

/usr/lib64/libopenjp2.so.2.3.0
/usr/lib64/libopenjp2.so.7

2 ficheiros no total

linux-tr7s:/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw # qmake-qt5 pteid-mw.pro 
Project MESSAGE: Release build!
Project WARNING: PKG_NAME has not been set! Assuming PKG_NAME=pteid
linux-tr7s:/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw # make
cd pteid-poppler/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pteid-poppler/pteid-poppler.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pteid-poppler'
cd poppler && make 
make[2]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pteid-poppler/poppler'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pteid-poppler/poppler'
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pteid-poppler'
cd common/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/common/common.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/common'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/common'
cd dialogs/dialogsQT/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQT/dialogsQT.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQT'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQT'
cd dialogs/dialogsQTsrv/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQTsrv/dialogsQTsrv.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQTsrv'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/dialogs/dialogsQTsrv'
cd cardlayer/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/cardlayer/cardlayer.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/cardlayer'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/cardlayer'
cd pkcs11/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pkcs11/pkcs11.pro ) && make -f Makefile 
make[1]: Entering directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pkcs11'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/pkcs11'
cd applayer/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw/applayer/applayer.pro ) && make -f Makefile 
Project MESSAGE: Release build!
Project WARNING: PKG_NAME has not been set! Assuming PKG_NAME=pteid
Project MESSAGE: Compile pteidapplayer
Project ERROR: libopenjp2 development package not found
make: *** [Makefile:315: sub-applayer-make_first-ordered] Error 3
linux-tr7s:/tmp/autenticacao.gov-master/pteid-mw-pt/_src/eidmw #

Existe algum rpm para o opensuse 15.3 ? pois apenas encontrei o ficheiro:  aplicação pteid-mw-opensuse15.2.x86_64.rpm
No entanto penso que este rpm seja para o open suse 15.2
Ao tentar correr a aplicação esta nem arranca.
 
idguiV2  eidmw_en.qm  eidmw_nl.qm  pteiddialogsQTsrv
linux-tr7s:/usr/local/bin # eidguiV2  
eidguiV2: symbol lookup error: /usr/lib64/libxml-security-c.so.17: undefined symbol: _ZNK11xalanc_1_118Function7executeERNS_21XPathExecutionContextEPNS_9XalanNodeERKNS_11XalanVectorINS_10XObje
ctPtrENS_31MemoryManagedConstructionTraitsIS6_EEEEPKN11xercesc_3_17LocatorE
linux-tr7s:/usr/local/bin # 

Ou como consigo compilar o source code para o open suse 15.3

Cumprimentos,
Rui Meirinho

**Comment by agrr** [comment]
Boa tarde, 

para compilar em Linux em geral é necessário pacotes que incluem os _header files_ (.h) e estes no openSUSE têm o sufixo "-devel".
Nesse caso deve faltar instalar o pacote `openjpeg2-devel`.

Correto, o RPM 3.7.0 para openSUSE foi compilado no openSUSE 15.2, vamos atualizar a distro base na 3.8.0 que deverá ser lançada em breve.

**Comment by agrr** [comment]
Para utilizadores do OpenSUSE Leap 15.3 já está disponível o pacote RPM v3.8.0 da aplicação.
