### ISSUE TITLE
PinPAD Acrobat Reader Windows 10 21H2

### ISSUE THREAD

**Issue by nelsonfnunes** [amagovpt/autenticacao.gov#99]
Boa tarde

Após upgrade para o windows 10 21h2 a opção de desativação do PinPAD apenas funciona na aplicação Autenticação.gov v 3.7.0, nas outras aplicações, como por exemplo acrobat reader não aparece a janela para colocar o PIN mas pede para colocar o PIN no pinpad do teclado.

Antes de atualizar para a versao 21h2 este problema não acontecia, uma vez desativado o pinpad na aplicação do cartao do cidadao era transversal para todas as aplicações.

como posso resolver este problema?

cumprimentos,
Nelson Nunes

**Comment by agrr** [comment]
Pedimos desculpa pela demora na resposta. 

O comportamento descrito é estranho porque a opção para desativar a funcionalidade Pinpad só tem efeito na aplicação Autenticação.gov.

Nas outras aplicações Windows a aplicação vai pedir o PIN no pinpad ou no dialog normal do Windows dependendo da deteção do tipo de leitor que é feita através de um valor devolvido pelo driver do mesmo.

Portanto a diferença entre Windows 10 21H2 e anterior terá a ver com o driver do leitor de cartões instalado antes e depois do upgrade. 

Pela nossa experiência com leitores Pinpad se não estiver instalado o driver do fabricante o leitor funciona mas não é detectado como leitor com Pinpad, usando o driver genérico da Microsoft.

Para podermos diagnosticar melhor este comportamento deverá indicar que modelo de leitor está a utilizar e colocar aqui o log que se encontra no ficheiro:
`C:\Program Files\Portugal Identity Card\log\pteidmdrv.log`

**Comment by nelsonfnunes** [comment]
a nova versao da aplicação Autenticação.gov v 3.8.0 corrigiu o problema.
Obrigado :)
